### ISSUE TITLE
Algorithm Security Controls

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1107]
Disabling Parts of the API in Code to Prevent Catastrophic Failure  
- e.g.  As a hedge fund with a lot of holdings you would want to disable liquidate feature.

**Comment by herrold** [comment]
Perhaps as part of a 'default' install, a configuration file should be provided, with 'safe' defaults, and commentary in _comments_ -- heh -- about how to exit to enabling initially 'defaulted safe' setting, along with an out-link to narrative (a file in the setup, or even something more formal (a .md, or .txt accessible with 'lynx' or some other browser)

This has the benefit of providing a 'canary' setting of:
   I_AM_UNCONFIGURED true

so that a setup tool can perform 'wizard' type functions, but have an option:
  -- safe

to move matter identified as 'unsafe' back into a commented state, and re-set all safe again

**Comment by jaredbroad** [comment]
Merged in https://github.com/QuantConnect/Lean/pull/935
