### ISSUE TITLE
Get more information in timeouts.

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1115]
The primary algorithm manager executes this action for the algorithm thread:
```
var complete = isolator.ExecuteWithTimeLimit(_algorithmHandlers.Setup.MaximumRuntime, algorithmManager.TimeLoopWithinLimits, () =>
                        {
                            try
                            {
                                //Run Algorithm Job:
                                // -> Using this Data Feed,
                                // -> Send Orders to this TransactionHandler,
                                // -> Send Results to ResultHandler.
                                algorithmManager.Run(job, algorithm, _algorithmHandlers.DataFeed, _algorithmHandlers.Transactions, _algorithmHandlers.Results, _algorithmHandlers.RealTime, _systemHandlers.LeanManager, isolator.CancellationToken);
                            }
                            catch (Exception err)
                            {
                                //Debugging at this level is difficult, stack trace needed.
                                Log.Error(err);
                                algorithm.RunTimeError = err;
                                algorithmManager.SetStatus(AlgorithmStatus.RuntimeError);
                                return;
                            }

                            Log.Trace("Engine.Run(): Exiting Algorithm Manager");
                        }, job.Controls.RamAllocation);
```
When it times out we don't know where in the stack it happened. It would be helpful to have a stack trace / or more debug information at the moment the action is thrown.

**Comment by andrewhart098** [comment]
I couldn't seem to crack this one. In the `Isolator` class - where the timeout error is thrown - we are using a task to run the callback code. Since Task uses the threadpool it's tough to identify which thread is being used by the callback code. We could switch to using a thread instead of a task, but that would require significant Api changes and even then - the .NET apis for pulling a stack trace out of a thread are all marked as obsolete. There was an example of someone creating their own stack - but the tools they used were pay-for-use. There would also be an added overhead of creating a custom stack that could be retrieved. Regardless - here is the link: http://blog.stephencleary.com/2013/05/announcement-async-diagnostics.html

**Comment by jaredbroad** [comment]
Closing as no known solution.
