### ISSUE TITLE
Decouple orders from order requests.

### ISSUE THREAD

**Issue by dpavlenkov** [QuantConnect/Lean#127]
Modifying order instances to request changes to them is pretty risky. I could change the order processing to work from requests after the initial AddOrder point. That way order state will make sense: changes to it happen after the requested action is performed. What do you think?

**Comment by jaredbroad** [comment]
Agree its risky if threading & invalidation not handled properly. We've always wanted to make Orders immutable to prevent needing close monitoring of the order status. 

How would you layout the system -- can please you give a little more detail on the proposed solution?

**Comment by dpavlenkov** [comment]
Here's a minimally disrupting solution. On SecurityTransactionManager,
replace OrdersQueue with  OrderRequestQueue. All operations(submit, update,
cancel) are done with requests. If you want orders immutable, great.
TransactionHandler owns Order implementations. TransactionManager only
assigns a new OrderId and put's it in submit requests. Users only see
IOrder, after TransactionHandler puts them in TransactionManager's Orders
dictionary. We can also add a Task<IOrderRequestResponse> handle on
IOrderRequest to tell user whether it was successful. Am I on the right
track?

**Comment by dpavlenkov** [comment]
This should illustrate my point: in BrokerageTransactionHandler, line 411
<code> 411            if (_orders.TryGetValue(order.Id, out queued) && (queued.Status == OrderStatus.Submitted)) //partially filled?</code>

This can never be true, because SecurityTransactionManager first sets Order.Status to Canceled and then adds it to OrdersQueue.

**Comment by jaredbroad** [comment]
Ok excellent catch :) -- agree this low impact implementation would be a good first step: What do you think about this as the path

1. Remove OrderStatus.Update from the OrderStatus enum
2. Create OrderRequest objects (Submit, Update, Cancel) with base class OrderRequest.
3. Rename OrdersQueue -> OrderRequestQueue
4. Update QCAlgorithm helper methods to submit OrderRequests
5. Public Orders Dictionary can be made an explicit Implementation to hide it from Algorithms
6. TransactionHandler pull from the OrderRequestQueue, process requests.

**Comment by dpavlenkov** [comment]
I'll get on this. Can you elaborate on 5 ? I'm not clear what you mean.

**Comment by mchandschuh** [comment]
I believe the spirit of 5 is to prevent the algorithm from having direct access to the underlying order storage.

**Comment by dpavlenkov** [comment]
Yes, no problem. We'll hide things nicely.

**Comment by dpavlenkov** [comment]
Can you give me your reasoning for subclassing Order? I think it's a mistake because Order preserves identity but can change type. Even now Lean engine can convert Market to MarketOnOpen. Order remains the same, its type changes. Brokerages allow converting Limit Orders to Market, and probably can convert any order to any type. I'm not against subclassing, but Order does not fit. I am prepared to do away with subclasses, but I'll need your say so.

**Comment by mchandschuh** [comment]
The primary reason was to prevent some fields/properties from applying to some order types and not to others. For example, if I created a market order, but then the object had a property called StopPrice, I think that would be confusing and misleading. So ideally, whatever solution we decide on wouldn't have fields/properties that only apply given the value of some other field/property in the object.

**Comment by dpavlenkov** [comment]
Ok, I'll go with subclasses. For some reason I thought brokers allow
changing order types.

**Comment by bizcad** [comment]
What happens if the algo places a LimitOrder and it does not fill by the next bar?   If the price moved away from my Limit, my strategy, a Resolution.Minute strategy, calls for the to be cancelled if (!Securities[symbol].HoldStock). 

The current implementation of HandleCancelledOrder logs an error "Unable to cancel order with ID 123".  

In the case of the BackTestingBrokerage, there is no queue and the order has already been marked OrderStatus.Cancelled.  As dpavlenkov says, that error message is wrong because the order was cancelled. In that case, a quick fix would be to check to see if the _brokerage is of type BackTestingBrokerage and not Log the error.

It gets a little trickier if Securities[symbol].HoldStock is true. Network and broker latency could mean that the order was executed and the cancellation did not happen.  Will the order be marked as filled or cancelled?  The strategy needs to know so it do not duplicate orders.  

There needs to be a way for an algo to find out the status of an order, and the public Orders array is a good place to find out.  

Just my 2 cents.

Nick

**Comment by mchandschuh** [comment]
Currently you can override the `OnOrderEvent` in the algorithm to get all order status update events directly from the brokerage (mediated by the transaction handler). Also, on a minute resolution strategy, the odds of those sorts of concurrency issues are greatly reduced since most of the algorithm's time will be spent waiting for the next minute. As for second/tick strategies, the developer needs to be vigilant in verified order state. For example, if I want to submit an order because another order hasn't filled, I can submit the order, and cancel the open order, but if the next status update I get back is filled instead of cancelled, then I should cancel the other order as well.

**Comment by jaredbroad** [comment]
Closed by commit 9c1b0f4
