### ISSUE TITLE
Add Task Filters to Order Tickets

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#140]
Allow async callbacks/tasks based on filter criteria to order tickets.

Make sure it runs synchronously in backtest to avoid in-deterministic  backtests (e.g. ContinueWith() executing at different times).

**Comment by jaredbroad** [comment]
Discussion welcome, lets figure out how to do this elegantly :)

**Comment by dpavlenkov** [comment]
#123
You have event driven system. Reactive extensions and TPL Dataflow is the way to use it elegantly. On .NET I see no alternative. Rx gives you Linq over Observable, TPL Dataflow gives you deterministic action blocks and, well, data flow. I'm not even sure you need to deal with tasks on API level. We deal with message processing, and for that we need pub/sub, filters, action blocks, etc. That's why I recommend those two libraries and API based on Observable and/or SourceBlock
