### ISSUE TITLE
Open source user Interface

### ISSUE THREAD

**Issue by naicigam** [QuantConnect/Lean#141]
Hi, everyone! 

I am new to Lean and I noticed that there is no user interface for the open source version and I would be happy to create one. Do all the open source users use the console? Or does everyone create a UI for themselves?

I would love to have some input on the language to use and what the first features should be.

I think ASP.Net vNext will be a great technology to do this, since it is open-souce, multi-platform and self hosted. The first release of VS 2015 will be available in a couple of days, but I have already been using the RC and it looks great.

Thanks!

**Comment by jaredbroad** [comment]
Hey Naicigam! We actually have a super simple one which we submitted as a
proof of concept but I'd really welcome your help with it!

We went with Win Forms since its 100% cross platform. You can see the demo
in the UserInterface project on Lean. To load with an interface you just
need to change your config environment to be desktop.

I'd be happy to consider vNext as long as its stable and supports
Win/Mac/Linux desktop charting.

Best,
Jared
