### ISSUE TITLE
How do I create an ATR indicator from a RenkoConsolidator source

### ISSUE THREAD

**Issue by sblanchard** [QuantConnect/Lean#143]
In the RegisterIndicator method it sees the outputType as Tick and throws an exception.
Is this possible to?

**Comment by mchandschuh** [comment]
In order to compute the AverageTrueRange, a TradeBar input value is
required. If you'd like to use a RenkoConsolidator's output as the input
for the ATR, you'll need to do some projection from the RenkBar ->
TradeBar, or, you could write a new version of the ATR that takes RenkoBar
as an input value. Here's some code that will take the output of a
RenkoConsolidator and pas it through to the AverageTrueRange indicator. The
first two lines create and plot the usual ATR14. The next several lines
create and plot the ATR14 of the consolidated renko output. An important
note here: The AverageTrueRange of a Renko bar should always be in the
neighborhood of the RenkoBarSize. By definition, the RenkoBar is a range
bound bar, not a time bound bar, so the true range of bars for which range
is already defined, will be about the size of the bar!

I hope these code snippets help!

-Michael

            // compute the 14 period average true range of daily prices
            var atr14 = ATR(symbol, 14);
            PlotIndicator(symbol, atr14);



            // comute the 14 period average true range of $5 renko bars

            // define a $5 renko bar consolidator
            var renko = new RenkoConsolidator(5m);
            SubscriptionManager.AddConsolidator(symbol, renko);

            // define our ATR indicator
            var atr = new AverageTrueRange(14);

            // each time we get a new renko bar, this event will be fired,
            // we'd like to update our ATR indicator with this data
            renko.DataConsolidated += (sender, args) =>
            {
                // project the output renko bar into a trade bar and pass
that
                // into our atr indicator
                atr.Update(new TradeBar
                {
                    Symbol = args.Symbol,
                    Time = args.Start,
                    Period = (args.End - args.Start),
                    Close = args.Close,
                    High = args.High,
                    Low = args.Low,
                    Open = args.Open,
                    Volume = args.Volume,
                    Value = args.Close
                });
            };

            PlotIndicator(symbol, atr);
