### ISSUE TITLE
ToolBox Addition: InteractiveBrokersDataDownloader

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#1462]
I noticed that  Interactive Brokers historical  data is not an option for Backtesting. Is that correct?.  I wonder if there is any technical / licence / agreement  constraint that prevented this feature or it's just pending to implement.  Thanks.

**Comment by jaredbroad** [comment]
Using the IB API would require downloading the data for every backtest; it would be very slow & inefficient. For live trading it makes sense as the timeframes are different and users are using IB for live trading. Potentially you could use a Toolbox project for saving historical data into LEAN format on disk.

BTW you can use the user group for _application_ discussion (https://groups.google.com/forum/#!forum/lean-engine); e.g. applying things for your use case so the GH issues list is for bugs / feature requests etc.  

how to hack IB for historical data -> user group.
build ib-toobox-project for saving historical data -> feature for issues list.

**Comment by benjaminthedonkey** [comment]
Thanks @jaredbroad , I lean towards building a Toolbox project (new feature). This work will also include a new Market constant (IB) right? I imagine the Toolbox will have to receive a host name and port number of a running TWS instance. Anyways those are implementation details. If you agree I can attempt to solve this, I have some time in the upcoming weeks.

**Comment by jaredbroad** [comment]
Cool thank you. It should ideally reuse the IB Brokerage history provider implementation; and the config for any details it needs. We shouldn't need a new Market constant (markets are to separate securities with the same ticker). It should then use the LeanDataWriter to write the data to LEAN format.

**Comment by benjaminthedonkey** [comment]
@jaredbroad  I need a new Market value to differentiate forex tickers. I'm not sure if there is another way to do it.  Thanks.

**Comment by michaelsrew** [comment]
benjamin did you manage to find the problem?

**Comment by benjaminthedonkey** [comment]
@michaelsrew  no I didn't . This test is for Interactive Broker's GetHistory method. The logic makes multiple calls to the API in order to download the complete history.  For minute resolution, the calls are for one day of data at a time.  Duration = 1 D ( check  method  ConvertResolutionToDuration() ), but if one of this calls comes back  empty,  the loop exists with no  error.  I'm not sure, but I  think weekends days might come back empty an  exist the loop?.

**Comment by michaelsrew** [comment]
hm i tried to implement an ib downloader for minute data long time ago. but downloading data for sp500 would take long time so i decided to use the terminal at quantconnect.  this approach i found better so i could download stock prices and test it multiple times on the harddrive. 
so first you set the date where you want to start and the end date. it loops through from start to end and thats it you have the data on your drive. IB does not provide any data info or error i think want it is weekend because the request goes OK but returns nothing....so no error as i can remember. simply looping over the days and thats it. the advantage over a downloader is that you have the data localy. the historyprovider is i think for warming up and that stuff. but warming up can also work localy from harddrive i thought at least at the beginning.

**Comment by benjaminthedonkey** [comment]
@jaredbroad  approach was to reuse IB history provider for the  downloaded. And It can be done as long as the history provider does what it's supposed to do. But in my test case is not doing that due to the problem I described. Maybe someone else can take a look and confirm whether or not this is a problem on IB history provider.

**Comment by michaelsrew** [comment]
aaahhh ok you want to use the history provider for the download now i get it. i will take a look at your test file in an hour when i get home.

**Comment by michaelsrew** [comment]
but to be clear...what i wanted to say.....the api of IB will not give you minute data for 10 days.....
due to limitations you get one day:
https://interactivebrokers.github.io/tws-api/historical_limitations.html#gsc.tab=0
so maybe the request is send for 10 days and IB returns only one day(the last day)
that is perhaps the problem.....thats why the while loop....loop through the days because API sends only one day minute data per request.

**Comment by StefanoRaggi** [comment]
@benjaminthedonkey @michaelsrew 
The IB History method had a couple of bugs (#1637) when requiring more than one API call to complete the request and a fix (#1669) has been submitted.

**Comment by benjaminthedonkey** [comment]
Sounds good, thanks. I'll try to complete this by next week.
