### ISSUE TITLE
When Multiple Live Custom Quandl Streams; Data Doesn't Arrive

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1486]
When running multiple live custom data streams from quandl data doesn't arrive in OnData; 

Added example main file; the QuandlFuture type standard 
[main.txt](https://github.com/QuantConnect/Lean/files/1640674/main.txt)
[dataobjects.txt](https://github.com/QuantConnect/Lean/files/1640681/dataobjects.txt)
[vxxcustom.txt](https://github.com/QuantConnect/Lean/files/1640685/vxxcustom.txt)
[xivcustom.txt](https://github.com/QuantConnect/Lean/files/1640686/xivcustom.txt)

**Comment by mchandschuh** [comment]
I was just looking into this and the issue is hourly quandl data. We do checks when polling remote files to ensure we don't pump stale data into the algorithm. When using hourly resolution, we'll only push the data into the algorithm if it is *at most* an hour old. Since we can never be sure as to when Quandl will post their new data, the recommendation is to always use daily data with Quandl to ensure the value gets piped into the algorithm instance.

**Comment by StephenOehler** [comment]
Hi Michael,

I used to use daily, but the problem then is that I only receive the data at midnight.  This futures data is published around 3pm EST and I need to get to it shortly right after it is published (preferably an hour after).  Setting the resolution to Daily will mean that my algorithm is effectively 9 hours behind the curve.  I set the resolution to hourly, knowing it was only a daily resource, because I wanted the algorithm to poll for the new data every hour.

Does that make sense?  I may be making this unnecessarily complicated by not knowing something crucial here.

Thanks again to you both for looking into this, by the way.

**Comment by StephenOehler** [comment]
On other thing I wanted to add: prior to a few months ago when this issue started, I had no problems polling Quandl hourly.  The algorithm worked well and then something happened to make the data feed just disappear.  Not sure what happened on the backend, but the main algorithm hadn't changed.

**Comment by jaredbroad** [comment]
@StephenOehler; I think MIke means by 1am the data won't be returned again; so you'd need to save the value somewhere and use that when the futures bar comes in. 

"make the data feed just disappear" -- you mean it stopped being pushed into your algorithm multiple times? I think we disabled fill forward on custom data a while ago -- maybe this is what you relied on

**Comment by StephenOehler** [comment]
Is there a way I can poll Quandl daily at a specific time in the day?  Not just at midnight?

**Comment by mchandschuh** [comment]
@StephenOehler - When using remote files with daily resolution, we'll continue to poll the remote source every ~30 minutes looking for new data. If the new data is less than a day old then we will emit it to the algorithm when the `EndTime` has come.

For example, the most recent data point from `SCF/CBOE_VX2_EW` is time stamped as `2018-01-16`. If we set that value to `Quandl.Time` then `Quandl.EndTime` will be `2018-01-17` since [`Quandl` data is configured as daily](https://github.com/QuantConnect/Lean/blob/d4bbeca1b3e52bb2ab08bbbbdaec4c322c182e8e/Common/Data/Custom/Quandl.cs#L57). So once midnight of the 17th rolls around, we'll emit the data generated on the 16th, or if the data comes in *after* midnight on the 17th but before midnight of the 18th, then we'll emit the data immediately. If data for the 16th comes in after midnight of the 18th, then we won't emit the data because it's older than 1 day.

In my test, the `SCF/CBOE_VX2_EW` futures data for the 16th was emitted to the algorithm on the 17th at ~12:23 EST (17:23 UTC):
```csharp
public override void OnData(Slice data)
{
    var keys = string.Join(",", data.Keys);
    Log($"{DateTime.UtcNow:o}:: Algorithm.OnData:: {data.Time:o}: Keys: {keys}");
}
```
Generated the following log:
```
2018-01-17T17:23:05.2068430Z:: Algorithm.OnData:: 2018-01-17T12:23:05.2029450: Keys: SCF/CBOE_VX2_EW
```

This seems like its coming in late, but checking quandl's website, they say the data was only updated 9 hours ago, which would be ~2:30EST, but the algorithm received the data at 12:23 EST (which is earlier).
![image](https://user-images.githubusercontent.com/531416/35081077-c1b74608-fbdf-11e7-91a0-80bb0831c158.png)

I also confirmed that the correct data point was emitted to the algorithm.

In addition, you can keep track of the latest values in the algorithm using something like the following:
```csharp
// class member
private Dictionary<Symbol, BaseData> customData = new Dictionary<Symbol, BaseData>();

public override void OnData(QuandlFuture data)
{
    customData[data.Symbol] = data;
}
```

Then you can access the latest value from your algorithm by:
```csharp
var latestVX2_EW = customData["SCF/CBOE_VX2_EW"] as QuandlFuture;
if (latestVX2_EW != null)
{
    // do something with data
    // the only time this would be null is before the data was set
    // this is possible if launching the algorithm on a sunday where the latest data is > 1 day old
    // you can also check the data's `EndTime` property to see how old it is
}
```

**Comment by StephenOehler** [comment]
Michael, thanks so much for looking into this.  So if I'm reading this right, I can safely set this to Daily resolution and it will pump futures data as it comes out?

Is the "polling every 30 minutes" a new thing?  Because I recall when I set it on Daily a year ago it only printed received data at midnight in live mode (i.e. the algorithm used to only check custom feeds only once a day).  I could be remembering wrong...

I just re-deployed the Multi-Feed test algorithm with both futures set to Daily to see how it pans out.  :-)

**Comment by StephenOehler** [comment]
Michael, I think we can mark this as closed.  I'm now receiving data for the futures streams when set to "Daily" :-)  Thank you!

**Comment by jaredbroad** [comment]
Thanks for letting us know Stephen!

**Comment by StephenOehler** [comment]
Just a heads up, we may need to re-open this ticket.  I deployed my main algorithm live and the continuous futures DID come in on the first day, but then stagnated for two days after.  I.E. it received daily data only once, then failed to receive daily data for the next two days.

I’ve redeployed the MultifeedTest again in live mode.  If I determine the problem exists there too, we may still have problems with this particular feed…

-Stephen

**Comment by jaredbroad** [comment]
From @StephenOehler 
```
Made more progress on the data stagnation front: I've figured out that QuandlFutures updates seem to die after the weekends. I ran my algorithm live on two separate occasions to verify this. Each time I started on a Monday, and each time the next Monday came around, QuandlFuture stopped sending daily updates. I have logs to share via email if you'd like to see them.
```
and
```
It only seems to be a QuandlFutures issue, and affects one stream or the other and sometimes both. Kinda inconsistent. No problems with any other data source types.

Another thing: today the streams picked the QuandlFutures feeds back up again. So it took two days to get back on track, but it did eventually do it.
```

**Comment by StephenOehler** [comment]
Hi guys, were you able to reproduce the "weekend vulnerability" in any fashion?

Also haven't heard back on the algo randomly up and dying due to the following:

"Runtime Error: System.Exception: Set Server Log Level Sending Error - Stack Trace: System.Exception: Set Server Log Level Sending Error - 
User: 17357, Project: 779009, Algorithm: L-0359ed25114a9762b35d5c240f6700c3"

**Comment by StephenOehler** [comment]
Restarting Multifeed test again; we'll see how it goes over the weekend.

**Comment by mchandschuh** [comment]
@StephenOehler -- Just merged (another) fix for this into `master`. We're launching a test algorithm that will be running for the next few weeks to confirm everything is working as expected. Feel free to deploy your algorithm as well and we can compare notes :)

**Comment by StephenOehler** [comment]
Thanks Michael!  I'll restart my test algorithm Monday to see how it goes.  :-)
