### ISSUE TITLE
Implement Futures' settlement price

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1488]
_A [settlement price](https://www.investopedia.com/terms/s/settlementprice.asp), in the derivatives markets, is the price used for determining profit or loss for the day, as well as margin requirements._ 
This key information is missing from Lean, but QuantConnect should have AlgoSeek.

**Comment by Martin-Molinero** [comment]
_"and it is important because it determines whether a trader is required to post additional margins. "_ note that Lean is already modeling margin requirements based on historical margins per future asset and unrealized profit per future holding is also available using the latest price at all times.
Summary: I think we don't really need this feature today
