### ISSUE TITLE
Indicator Fetching / Cache

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1492]
Often people don't realize the indicator methods return an object; and calling it over and over again just returns a new indicator object. IMHO we can safely assume people only want 1 copy of an indicator; and subsequent calls to the method should return the matching indicator from the cache.

This would make syntax like this possible:

`if ( SMA("SPY", 10) > SMA("SPY", 50) ) `

Since we'd be returning objects from the cache instead of recreating them each time.

**Comment by Worthy7** [comment]
How would these be initialized?

**Comment by jaredbroad** [comment]
Interesting point. Currently people improperly using the indicators aren't warming them up / initializing them. So this wouldn't be a change for them.  In general though yes it would be much better if the indicator objects returned from the SMA method warmed up (via internal method).  

Kind of means this syntax also needs the indicators to be pre-warmed; making it a breaking change for everyone currently warming up their indicators.

**Comment by Worthy7** [comment]
Not necessarily, just check if they are warm or not when they are first called, use history to warm them. Not efficient at all but would make it work.

**Comment by mchandschuh** [comment]
Another option long mulled over is maintaining some history locally (previously considered expanding the cache to support this, not sure the best route though). This could serve many purposes, first allowing history calls to check memory first to see if we already have it, and second, support auto-warming indicators/ect.

**Comment by Worthy7** [comment]
@mchandschuh I actually wrote that in my previous comment but then deleted it because it's very hard to decide how big it needs to be, and causes overhead.  Perhaps we could have some kind of default history, that is like, 200 big (of whatever), and then if an indicator requests more than that, error and tell the user they need to initialize it manually in that case? Just an idea... not sure if it's a good one :D

**Comment by mchandschuh** [comment]
In order to maintain references to the indicator so we can serve it back, we'll need to keep some definitional object, which presumably could include the required warmup period. In the beginning, we have no data so history would be the only way. As the algorithm progresses, however, we'll have an idea as to how much we need.

That being said, this is precisely we it was never implemented. The solution would undoubtedly be filled with heuristics for determining optimal cache length while also adding memory pressure by default (unacceptable IMO).

I think an acceptable first step is to cache to indicators according to some definitional object. This could be managed solely by QCAlgorithm or could also be a method on the indicator to return a definitional object. From an OPP standpoint, it would seem to be the concern of the indicator to provide it's own definitional object and the concern of QCAlgorithm to cache indicators using the definition as a key.

**Comment by Worthy7** [comment]
After some more thoughts, I think we shouldn't do any of the above really...

@jaredbroad This problem is just because people are not reading the docs properly. We shouldn't make complex workarounds for those people IMO. Sorry but we have to get strict at some point to our users, and in this case, they are supposed to be programmers too. Maybe there are a lot of beginners using QC...

The best point I can come up with why this is not worth it, is that either way, even if this functionality was implemented, we would write an alias for it like so : `mySma = SMA("SPY", 20)`. And, surprise, this is exactly how it initializes anyway. I think you guys have done a great job already. @mchandschuh even if we had a cool cache, any programmer worth his salt is not going to write `RSI('SPY', 40, MovingAverageType.Exponential)' all through `OnData`, it will be mapped to a variable anyway, which is where it could have initialized if people read the docs.

What we could do, is either rename SMA, or make it an instance object shorthand `new SMA` so it is more clear that way. SMA is a factory method essentially, which makes me think it should have the word `Create` or `Get` in there somewhere. But I guess the reality is, we just wanted to make `new SmoothMovingAverage` shorter.

So the problem seems to be, that it is not clear SMA is a Factory function, causing people to use it in the wrong way.

**Comment by StefanoRaggi** [comment]
Although the indicator cache and reusing call syntax is commonly used in retail trading platform script languages, I'm not sure I like this feature for reasons already discussed above (warmup, history, IsReady usage, etc.)

I agree with @Worthy7 about the docs and factory methods, also because we also have to support Python which doesn't have the `new` keyword, so same syntax for class constructor and factory function call :)

Perhaps we could use an indicator cache keyed by the `Name` property, just to prevent people from creating the same indicator multiple times.

**Comment by jaredbroad** [comment]
"Perhaps we could use an indicator cache keyed by the Name property, just to prevent people from creating the same indicator multiple times." -- this is exactly what the Issue was for about :D

**Comment by StefanoRaggi** [comment]
Sorry if the phrase was incomplete, by _prevent_ I meant adding the cache only to check if present **and** throw an error message if found.

I was suggesting this syntax be explicitly forbidden, not allowed :) 
`if ( SMA("SPY", 10) > SMA("SPY", 50) )`

**Comment by jaredbroad** [comment]
Good idea!

**Comment by Worthy7** [comment]
Coincidentally, I was working on an extremely basic algorithm these last 2 days (trying to make the init class as simple as humanly possible, and it's very clear that because we need to ping "IsReady" of every indicator registered, that it would be worth at least holding a cache of all registered indicators. It's for a separate reason, but that's 2 reasons to actually make the cache. I think on registration of the indicator, cast to IIndicator<IBaseData> (?) and throw it in a dict or list or something. I am struggling with this part I thought they would all just happily go into an IEnumerable<IIndicator<IBaseData>>

```
using QuantConnect.Algorithm.CSharp.Core.Extensions;
using QuantConnect.Algorithm.CSharp.Core.Indicators;
using QuantConnect.Algorithm.CSharp.Ian;
using QuantConnect.Data;
using QuantConnect.Data.Market;
using QuantConnect.Indicators;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace QuantConnect.Algorithm.CSharp.BabyPips
{

    /// <summary>
    /// I wanted to design a very simple system that can be coded very easily. I used this page:
    /// https://www.babypips.com/learn/forex/build-your-trading-system
    /// 
    /// It very clearly defines:
    /// 1) Define your time frame
    /// 2) Determine your entry triggers
    /// 3) Determine your exit triggers
    /// 
    ///  =Setup=
    ///  Trade on daily
    ///  5 SMA on close
    ///  10 SMA on close
    ///  Stochastic (14, 3, 3)
    ///  RSI(9)
    ///  
    /// 
    /// =Trading Rules=
    /// _EntryRules_
    /// Long if:
    ///    5 SMA crosses above 10 SMA 
    ///    and both stoch are heading up
    ///    and stoc lines not in overbought
    ///    and RSI > 50
    /// Short if:
    ///    5 SMA crosses below 10 SMA
    ///    and both stoc lines heading down
    ///    and stoc not in oversold area
    ///    and RSI lessthan 50
    ///  
    /// _exit rules_
    /// - 5 SMA cross 10SMA in opposite direction of trade
    /// OR RSI crosses 50
    /// OR hits stop loss 100 pips.
    /// 
    /// </summary>
    public class MovingAverageCrossoverSystem : IanForexBase
    {
        private SimpleMovingAverage FiveSMA;
        private SimpleMovingAverage TenSMA;
        private Stochastic stochastic;
        private RelativeStrengthIndex rsi;
        private RollingWindow<IBaseData> rollingStochasticStochK;
        private RollingWindow<IBaseData> rollingStochasticStochD;
        private RollingWindow<IBaseData> rollingFiveSMA;
        private RollingWindow<IBaseData> rollingTenSMA;
        private RollingWindow<IBaseData> rollingRSI;

        public override void Setup()
        {
            SetSymbol("USDJPY");
            resolution = Resolution.Daily;

        }

        public override void Conditions()
        {

            FiveSMA = SMA(symbol, 5, resolution, (a) => ((QuoteBar)a).Close);
            TenSMA = SMA(symbol, 5, resolution, (a) => ((QuoteBar)a).Close);
            rollingFiveSMA = CreateRollingWindow(FiveSMA, 2);
            rollingTenSMA = CreateRollingWindow(TenSMA, 2);
            stochastic = STO(symbol, 14, 3, 3, resolution);
            rsi = RSI(symbol, 9, resolution: resolution);
            rollingStochasticStochK = CreateRollingWindow(stochastic.StochK, 2);
            rollingStochasticStochD = CreateRollingWindow(stochastic.StochD, 2);
            rollingRSI = CreateRollingWindow(rsi, 2);

            IsWarm = () =>
            (
                FiveSMA.IsReady &&
                TenSMA.IsReady &&
                rollingFiveSMA.IsReady &&
                rollingTenSMA.IsReady &&
                stochastic.IsReady &&
                rsi.IsReady &&
                rollingStochasticStochK.IsReady &&
                rollingStochasticStochD.IsReady &&
                rollingRSI.IsReady
            );

            EntryLongConditions = () => (
                rollingFiveSMA.CrossedAbove(rollingTenSMA) &&
                    rollingStochasticStochK.IsRising() && rollingStochasticStochD.IsRising()
                    && !(stochastic.StochD.Current > 70) && !(stochastic.StochK.Current > 70)
                    && rsi.Current < 50
            );


            EntryShortConditions = () => (
                rollingFiveSMA.CrossedBelow(rollingTenSMA) &&
                    rollingStochasticStochK.IsFalling() && rollingStochasticStochD.IsFalling()
                    && !(stochastic.StochD.Current < 30) && !(stochastic.StochK.Current > 30)
                    && rsi.Current < 50
            );

            ExitConditions = () => (
                rollingFiveSMA.Crossed(rollingTenSMA, GetCurrentOrderDirection().Opposite())
                || rollingRSI.Crossed(50m)
                || Lossed(pips: 100m)
            );

        }

    }
}

```
This is the wrong place to discuss lots of improvements over lean based on this simple snipped, but it's the right place to say +1 to an indicator cache, just for the sake of automatic warmup check :)

**Comment by jaredbroad** [comment]
Good discussion. Miss you guys! @worthy7 @mchandschuh @StefanoRaggi
