### ISSUE TITLE
LeanData.TryParsePath should force date of data files to data timezone

### ISSUE THREAD

**Issue by ebengtso** [QuantConnect/Lean#1497]
Since this code parses the date from the filename, it takes the default timezone for the date. It should instead force to UTC

I propose to use this code instead
`date = DateTime.ParseExact(info[startIndex + 4].Substring(0, 8) + " -00:00", "yyyyMMdd zzz",  null);
`

**Comment by jaredbroad** [comment]
The dates in the "data" timezone (not UTC). The date value passed into the method should be in the right timezone already. 

LEAN has 2 key timezones -- data and exchange; exchange is the exchange open hours zone. Data is read off disk and immediately converted to exchange timezone. 

OANDA stores data in UTC but has EST/global exchanges. US Equities are EST/EST. etc. 
I think its safe to close this issue?

**Comment by ebengtso** [comment]
the method return date in default machine timezone, not in exchange or data timezone. I think that's why after I forced the code to return the date in UTC, it worked, because it matches oanda data timezone

maybe then title should not be "should force UTC time", and instead "should force date to data timezone"

**Comment by jaredbroad** [comment]
Its timezoneless at the moment; forcing into a specific timezone would return different results depending on the computer's timezone its tested on? Not sure that is a better result?

**Comment by ebengtso** [comment]
the whole thing is not clear to me, but it appears to me that it behaves like this when I run lean with a master version:
- my computer is on GMT+1
- the data files for Sunday are never downloaded

I expected sunday's files to get downloaded. These files would contain data the last hour of that day, since the market opens on sunday 23pm GMT. Instead the file is never downloaded. 

After my fix to UTC, which coincidentally is the data time zone, the files gets downloaded

**Comment by jaredbroad** [comment]
Got it thanks for the example; flagged as bug will get to it ASAP.

**Comment by StefanoRaggi** [comment]
Hi @ebengtso, 
I assume you are trying to download data with Lean using the `ApiDataProvider`.
There should be no need to change `LeanData.TryParsePath` as the date currently returned by `DateTime.ParseExact` does not and should not have time or timezone information (only the date).

I was unable to repeat your issue, with a simple algorithm using the `ApiDataProvider` all required data files are always downloaded (including Sunday data files), using current master code.

Since this issue was opened months ago, I would recommend trying again with latest master code (might have been a LEAN bug already fixed) and see if the issue persists.

Closing for now as not repeatable, if you still have the problem please feel free to reopen the issue and provide a repeatable test case.
