### ISSUE TITLE
Indicators to accept timespan

### ISSUE THREAD

**Issue by worthy7** [QuantConnect/Lean#1529]
Hi there, this is a suggestion firstly, as I couldn't come up with a relatively simply way to implement it.

At the moment we have the very nice `SMA(10)` style shorthand factory functions, which work great if we are using set resolutions, but I would like to see if we could make it easier for the 4 hour, or 15 minute timeframes too - to aid anyone working with other timeframes.

It seems straightforward to swap out all the innards of the shorthand indicator functions to work with TimeSpan instead, but doing it in a way that was backwards compatible seems a bit hard.
I first tried to make an autocast from the `Resolution` enum, but quickly found you cannot do that with enum types, only classes. So after this I tried adding a `timeSpan` parameter to *every* indicator shorthand. I did it, but it somehow just feels wrong, because now the function parameters are `..., resolution, selector, timeSpan` which just feels dirty.

Anyone have any thoughts? Thanks!

**Comment by Worthy7** [comment]
My current implementation looks like so. I don't really like having the `timespan.indicators` files, but it was easier to manipulate them like that. Just to show an idea really, could be cleaned later
https://github.com/Worthy7/Lean/commit/574b11dc79a81161ec82fe09e6d8181e725b8c7c

**Comment by AlexCatarino** [comment]
Hi @Worthy7, since you can convert `Resolution` into `TimeSpan`, you could implement this feature like this:
```csharp
public AccumulationDistributionOscillator ADOSC(Symbol symbol, int fastPeriod, int slowPeriod, Resolution? resolution = null, Func<IBaseData, TradeBar> selector = null)
{
    return ADOSC(symbol, fastPeriod, slowPeriod, resolution?.ToTimeSpan(), selector);
}

public AccumulationDistributionOscillator ADOSC(Symbol symbol, int fastPeriod, int slowPeriod, TimeSpan? resolution = null, Func<IBaseData, TradeBar> selector = null)
{
    var name = CreateIndicatorName(symbol, string.Format("ADOSC({0},{1})", fastPeriod, slowPeriod), resolution);
    var adOsc = new AccumulationDistributionOscillator(name, fastPeriod, slowPeriod);
    RegisterIndicator(symbol, adOsc, resolution, selector);
    return adOsc;
}
```
You will have to change `CreateIndicatorName` to accept `TimeSpan` instead of `Resolution` and tweak it a little bit.

**Comment by Worthy7** [comment]
@AlexCatarino Thanks for responding! I see.
So I could probably have written my code better.

I'm not a dot net expert, but is there some way to allow functions which accept `TimeSpan` to also accept `resolution` if the resolution class has some kind of automatic cast thing.. I can't recall how it works.
Basically what I'm thinking is;
1) Rewrite all Indicator functions to accept TimeSpan instead
2) make `Resolution.minute` auto convert to `TimeSpan.FromMinutes(1)` globally

That would bring custom timespan features into the default indicator functions, and allow backwards compatibility

**Comment by AlexCatarino** [comment]
Since `Resolution` is a not a `class`, it is an `Enum` (and `Enum` are already implicitly converted into integer). You we will have to write two methods per indicator where one accepts `TimeSpan` and the other `Resolution`... that is what we have done with other methods in Lean.

**Comment by Worthy7** [comment]
Well in that case it's exactly the same as my currently implementation then.

**Comment by AlexCatarino** [comment]
Right, but in you could simplify your current implementation by calling the more general method with `TimeSpan` parameter from the method with the `Resolution` parameter using `Resolution.ToTimeSpan()` extension helper method like I suggested above (that is what we would ask you to do if you make a pull request as it is). Maybe you could keep both overloads in the same file, one after the other, so that future indicator implementations don't miss any overload.

**Comment by Worthy7** [comment]
Ok, I think I follow. This was quite a while ago. So what changes exactly
would be perfect for a PR?

**Comment by AlexCatarino** [comment]
1. Follow [this pattern](https://github.com/QuantConnect/Lean/issues/1529#issuecomment-408864493);
2. Refactor `CreateIndicatorName` to accept `TimeSpan` instead of `Resolution`;
3. Keep all methods in one file (`QCAlgorithm.Indicators.cs`).

**Comment by mchandschuh** [comment]
fyi, it is very possible to have a single method accept both `Resolution` and `TimeSpan` -- it would require a  *third* type, say `ResolutionTimeSpan` that contains `implicit` conversions from `Resolution` and from `TimeSpan`

See https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/implicit

**Comment by Worthy7** [comment]
@AlexCatarino  @mchandschuh  This is what I was looking for.

**Comment by Worthy7** [comment]
@mchandschuh After briefly trying this, I realized I cannot convert `Resolution.Tick` to a `TimeSpan`.... So I think this is a NG

**Comment by biiiipy** [comment]
Any update on this? It kind of boggles my mind that this simple functionality is not baked in the API, since it's one of the most basic things people do.... And not resolved for 3 years? I don't understand, do people really not use MTF in their algos? Hard to believe.
And also, since the plumbing is there, it's just the API surface, this seems like a very easy thing to add, so what's the reason not to?

**Comment by jaredbroad** [comment]
- I think we made this easier with the Consolidate() helper. 
 - No further user demand since the creation of this issue; probably the current API is good enough for most people.

**Comment by biiiipy** [comment]
> * I think we made this easier with the Consolidate() helper.
> * No further user demand since the creation of this issue; probably the current API is good enough for most people.

I followed this issue years ago and got a notification about it getting closed, so here I am. Let me share some honest feedback to you. This issue was opened 5 years ago and you're closing this only now, for an essential, must-have, very typical use-case feature. It's funny cause it's sad.
"No further user demand" is a spot on observation, because nobody cares anymore (just like you didn't). 
"good enough" - it actually wasn't.

**Lean was my first tool for developing strategies, I thought that it will be great**, but instead it was a massive waste of time and energy. This issue is very indicative of why.
