### ISSUE TITLE
Don't use stale data for fills / or enforce fill on the next bar.

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1572]
Fill forward data creates confusing fill issues where old data is being used to fill orders. We shouldn't use it in setting the fill price. This is more accurate anyway as in reality you're always filled at the _next_ price not the previous one. 

`BaseData` has an `IsFillForward` flag. We can look at the flag in the models and only process the fill request when the next real bar arrives.

**Comment by DMTSource** [comment]
In the case of live trading on IB, a lack of data can cause some silent crashes or very large fill-times via SetHoldings due to lack of QC price data at open that was seconds away from arriving. If fills are waiting for the next available step in backtest, would it be possible to add an async behavior to all orders to allow for them to act similarly in live without blocking behavior?

**Comment by jaredbroad** [comment]
The data hasn't arrived yet and in reality there's no way of knowing how long it'll be before a fill is processed - especially for larger orders. All orders already do support async behavior (async true flag).

Sadly making all orders async would be a breaking change for most users who rely on immediate market fills. Possibly we can compromise with a way of determining "stale" data (e.g. older than 1 min).

**Comment by jaredbroad** [comment]
Second example of this -- using minute data + scheduled events for middle of the day --> then placing market orders for a daily resolution asset. The asset will be filled at the market-close yesterday price.

Could also be solved by the stale-data concept described above but its not limited to fill-forward data..

**Comment by DMTSource** [comment]
Using coarse universe in minute mode, and Scheduling for 0-0.99 minutes after market open seems to give the previous days data as well for most fills(this was my original problem since Oct/Nov 17). It would be great if I had gotten errors instead of bad fills, I could have forced my code into OnData and waited for the data and gotten slightly realistic fills. Maybe if the Logs showed times relating to the fills it would be easier to not get tricked by results?

**Comment by jaredbroad** [comment]
"Scheduling for 0-0.99 minutes after market open seems to give the previous days data as well for most fills" -- @DMTSource correct; its using the fill forward data for the fill price. We should make it use the _next_ bar ideally to make it obvious.  

I don't think this is a bug; it is just an easy misuse of LEAN based on misunderstand of the data. But we can make it more difficult to encounter this setup.
