### ISSUE TITLE
GDAX CanSubmitOrder Doesn't Reject Shorts

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#1576]
Shorts are not supported with cash modelling on GDAX. We should reject them outright. This is causing SetHoldings("BTCUSD", -1) to hang. 

We need to update  `GDAXBrokerageModel.CanSubmitOrder` to check for shorts -- so the transaction handler will flag the order as invalid and it should exit the wait for market order loop.

**Comment by Jay-Jay-D** [comment]
I cannot reproduce a hanging on the `SetHoldings("BTCUSD", -1)` in backtesting mode. Happens that the short order is not executed, and the `SetHoldings("BTCUSD", -1)` is called for every new `OnData` because [`Portfolio.Invested == False`](https://github.com/QuantConnect/Lean/blob/5eabec08b52e7606c4a6a2b8dfc14935009917a0/Algorithm.CSharp/BasicTemplateCryptoAlgorithm.cs#L53).

In turn, the short order is never executed because, given the `AccountType.Cash` for the GDAX broker, a short order will never reach the `GDAXBrokerageModel.CanSubmitOrder`. The order size will be zero from the [`CashBuyingPowerModel.GetMaximumOrderQuantityForTargetValue`](https://github.com/QuantConnect/Lean/blob/5eabec08b52e7606c4a6a2b8dfc14935009917a0/Common/Securities/CashBuyingPowerModel.cs#L143) method.

So, in principle, the solution is throwing an exception from the `CashBuyingPowerModel.GetMaximumOrderQuantityForTargetValue` method. What do you think?
