### ISSUE TITLE
Add Universe Selection feature in QuantBook

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1614]
#### Expected Behavior

In QuantBook, it should be possible to use the Universe Selection feature.

#### Actual Behavior

Not supported.

#### Potential Solution

N/A

#### Reproducing the Problem

N/A

#### System Information

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
We're back and forth on this one's design;
 - Concept 1 is to make notebooks an algorithm in an engine, where the engine steps through time. The advantages are lower maintenance and all the existing APIs would work immediately. The weirdness is that its a very nonstandard way to do interactive research that would require the user to step through time. 

 - Concept 2 is to make new batch-focused helper methods for each primary API method and do history requests and data frame conversions to get all the data into a friendly format. This is the current design.

Typically we'd be plan 1, but it feels strange and not jupyter friendly.

Leaving open; a solution with the current design would be to make a helper like this:
`symbols = GetUniverseSelection(date, filter Coarse, filterFine)`

Then the community could load the history for those indicators and do any batch analysis they prefer.

We've been hesitant to implement because its further down a pathway that requires heavier maintenance and new API methods.

**Comment by pavelfedorov1** [comment]
To avoid a look ahead bias without a universe of stocks for each date,, how would one create a dataset for machine learning to train our models on fundamentals data? using arbitrary symbols creates look ahead bias since we need to access delisted symbols from past years to build the dataset without lookahead bias

**Comment by jensakut** [comment]
Hi! 

What about a combination of Concept 1 and Concept 2. When creating a Universe Selection, run through time and keep tabs on which symbols went into the Universe as defined in a coarse/fine function as well as interesting data. With this table of date, symbol, data1, ... dataN, the Jupyter can be filled. 
Currently, a backtest, the data storage (with a subscription), and Jupyter notebook can be used for such an endeavour. 

Best
