### ISSUE TITLE
ATR calculations do not follow J. Welles Wilder's book instructions

### ISSUE THREAD

**Issue by ThomasSzabo** [QuantConnect/Lean#1722]
Like the RSI test data (as I already reported here https://github.com/QuantConnect/Lean/issues/1651), I found that the test data for the `Average True Range` is not correct either.

Here is the link to your test data:
https://github.com/QuantConnect/Lean/blob/master/Tests/TestData/spy_atr.txt

If your ATR indicator is tested against this data and successfully passes the test, it is likely that the algorithm is not based on the original ATR developed by J.W. Wilder.

Please download the test data from stockcharts. They got it right:
http://stockcharts.com/school/doku.php?id=chart_school:technical_indicators:average_true_range_atr

Take the stockcharts data and feed your indicator with it. Do the results match?

**Comment by jaredbroad** [comment]
Hi @ThomasSzabo. Please submit issues using the template provided -

**Comment by ThomasSzabo** [comment]
Wow. I wish you a good life and happiness @jaredbroad

**Comment by AlexCatarino** [comment]
@ThomasSzabo We ask contributors to follow the template in order to accept the issue in order to lead them to provide strong proves that our calculations and/or test data are incorrect. Often people just don't understand the issue well and QuantConnect team spend previous time running after a "feeling". I am not saying it is your case, but it could be.
I took the [data from stockcharts](http://stockcharts.com/school/lib/exe/fetch.php?media=chart_school:technical_indicators_and_overlays:average_true_range_atr:cs-atr.xls) and plugged it in our unit test. 
First, our test assumes that a simple moving average is used to smooth the data whereas the stockcharts assume Wilders' moving average. Therefore our data is not incorrect, it only assumes a different smoothing function.
Then I changed the smoothing function and, in fact, our computations doesn't follow Winder's definition as in his definitions the initial ATR is the simple mean of the previous True Range values while we apply the smoothing function from the start.

**Comment by AlexCatarino** [comment]
#### Expected Behavior
The initial `AverageTrueRange` value is the **simple** mean of `True Range` values.

#### Actual Behavior
The initial `AverageTrueRange` value is the **weighted** average of `True Range` values.

#### Potential Solution
Use a simple moving average to compute the initial `AverageTrueRange`.

#### Reproducing the Problem
Take [data from stockcharts](http://stockcharts.com/school/lib/exe/fetch.php?media=chart_school:technical_indicators_and_overlays:average_true_range_atr:cs-atr.xls) and plugged it in `AverageTrueRangeTests`.

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue
