### ISSUE TITLE
Set Price property of FineFundamental instances

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#1735]
#### Expected Behavior
`FineFundamental.Price` value is the current price of the security. 

#### Actual Behavior
`FineFundamental.Price` value is zero.
The `FineFundamental` class contains only fundamental data from Morningstar, it has the `Price` property because derived from `BaseData`, but its value is never set (and is also not contained in the fine data files).

#### Potential Solution
Set the price property when creating the new `FineFundamental` instance, reading it from `Security.Price`.

#### Reproducing the Problem
Run any Universe Selection algorithm and check whether `FineFundamental.Price` of each symbol is zero.

#### System Information
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
This is tough since the fundamental data emits at most daily, so best we could do is provide yesterday's closing price, which is now available via `security.Fundamentals.Price`

**Comment by mchandschuh** [comment]
@jingwu74  -- does having yesterday's closing price fill your need, or do you require it to be the *current* security price? The reason I lean towards not supporting the current price is because that data is available via `security.Price` -- also, in the selection functions, the 'current' price is slightly ambiguous (do we include post-market prices?) -- so I think using yesterday's close is the best bet -- another reason is that yesterday's closing price is part of the coarse data set which is where the other properties on `security.Fundamentals` come into play.

**Comment by jingwu74** [comment]
I'd go along with yesterday's closing price as the other fundamental data are all in less frequent resolutions and it is ambiguous to set the current price for after hours. Is it raw closing price or adjusted price?
