### ISSUE TITLE
EndTime in TradeBar using the History function possibly incorrect

### ISSUE THREAD

**Issue by chrisdk2015** [QuantConnect/Lean#181]
EndTime in TradeBar is supposed to be closing time.

So for a daily bar 30th of september, EndTime should be 30th of september, no?

Because I am using the History function and there seems to be an offset of 1 day.

For BIB

Date / Open / High / Low / Close / Volume / Adj.close

Oct 8, 2013	128.50	128.85	117.32	117.51	559,600	29.38
Oct 7, 2013	132.08	132.66	128.65	128.69	177,200	32.17

If I have the following code

// get the last calendar day's worth of SPY data at the specified resolution
            tradeBarHistory = History("BIB", TimeSpan.FromDays(1), Resolution.Daily);

using the dates

SetStartDate(2013, 10, 07);  //Set Start Date
            SetEndDate(2013, 10, 11);    //Set End Date 

I get a tradebar with EndTime Oct 8, 2013 

Date / Open / High / Low / Close / Volume / Adj.close

Oct 8, 2013	132.08	132.66	128.65	128.69	177,200	32.17

A bug?

I encountered this because I was feeding my algorithm with historical data and then I had suddenly two bars for the same day: one live and one historical.

**Comment by chrisdk2015** [comment]
https://drive.google.com/file/d/0B95K6AyeZ37SNDVQZmpLbDk5VUE/view?usp=sharing

Bib.zip

and 

https://drive.google.com/file/d/0B95K6AyeZ37STVNKUE9tbU9mbGM/view?usp=sharing

screenshot of monodevelop in debugger.

**Comment by mchandschuh** [comment]
The daily data on October 7th is dated as follows:
`bar.Time` will be midnight on October 7th
`bar.EndTime` will be midnight on October 8th

**Comment by chrisdk2015** [comment]
I see, so I got confused by intellisense, it was hiding Time from the base class.

**Comment by mchandschuh** [comment]
Looks like a possible bug in `SubscriptionDataReaderHistoryProvider` -- the bar end times are fine, it just appears to be grabbing the wrong data. Possibly need to back out the resolution in the request object since the `SubscriptionDataReader` has filters that allow any overlap (time->endtime) with requested interval.

In your example, that function call should return zero elements, since 2013.10.07 is a Monday and the function overload that accepts a `TimeSpan` uses calendar days. It appears the correct behavior happens if you request 1 bar instead of 1 day of Daily data:
```C#
var tradeBarHistory = History("SPY", 1, Resolution.Daily);
```
This returns 1 bar from the previous Friday (end time midnight Saturday morning)

**Comment by mchandschuh** [comment]
More information, the reason this is a bug is because when requesting daily data on October 7th you shouldn't be able to get the daily data FOR October 7th (end time October 8th), this would be blatant look ahead bias as you would be able to retrieve the close of the current day.

Have a fix working locally, will push shortly. Thanks for reporting the bug!!

**Comment by chrisdk2015** [comment]
Aha, it makes sense, since of course you cannot request historical data in advance.

Sometimes just fiddling around with the code will expose such things! :)

**Comment by mchandschuh** [comment]
Fixed in https://github.com/QuantConnect/Lean/commit/5fadd0466a1346b8032126920687f592a63f23fe
