### ISSUE TITLE
Inconsistency between SetHoldings(symbol,0) and Liquidate(symbol) for Crypto-Currencies

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#1860]
#### Expected Behavior
The two methods should _probably_ be functionally equivalent, which one is "correct" is still to be decided.

#### Actual Behavior
The two methods behave differently when starting the algorithm with existing holdings for the symbol:
- `Liquidate("BTCUSD")` -- liquidates only holdings bought since the algorithm was started, not counting initial holdings
- `SetHoldings("BTCUSD", 0)` -- liquidates totally, leaving cashbook for BTC empty

#### Potential Solution
This issue is open for discussion.

#### Reproducing the Problem
The issue can be easily reproduced by manually testing the two statements above and adding this line in `Initialize`:
``` C#
SetCash("BTC", 1m, 0m);
```

#### System Information
n/a

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Debate is whether we should design LEAN towards:

1) Virtual Positions are the main focus of the portfolio (as it is now). This standardizes the behavior of other asset classes with crypto-cash-modeling; but means the cashbook (used for order buying power) and the virtual positions can get out of sync resulting in weird states.

2) Making cash modelled virtual positions purely pass throughs to the cashbook and *fictional*. So summing them could actually look like we have more than we do: 1 BTC, 1 LTC and 1 USD would give us virtual positions from:
```    Portfolio["BTCUSD"], Portfolio["LTCBTC"], Portfolio["LTCUSD"],   ```

Liquidate() simply sells the virtual holdings... so if have never made a trade it won't do anything.
SetHoldings(0) now uses the cash buying power model to figure out the cash book coins available....

Additionally, liquidate to what currency? For now we should implement to Cashbook.AccountCurrency (USD) --> so all crypto holdings should be sold off into USD? We might need to do full non-USD-base-currency support to implement it nicely (https://github.com/QuantConnect/Lean/issues/110).

Personally I lean towards making number 1 work as it'll be the closer to the other asset classes. I see the current cash-only trading on Crypto as a temporary restriction due to newness of crypto. Odds are they will move to offering same features of traditional forex-brokerages (margin, virtual positions).

**Comment by viliwonka** [comment]
I tried to do "Cashbook.AccountCurrency to ETH", and lots of Unit test have failed, so for now I have it at USD. I could help with making Lean support ETH, since I would prefer it.

**Comment by Martin-Molinero** [comment]
> The two methods behave differently when starting the algorithm with existing holdings for the symbol:
    Liquidate("BTCUSD") -- liquidates only holdings bought since the algorithm was started, not counting initial holdings
    SetHoldings("BTCUSD", 0) -- liquidates totally, leaving cashbook for BTC empty

This behavior is no longer happening and we currently fully support initial virtual holdings for live trading for crypto.
