### ISSUE TITLE
ConstantAlphaModel should exclude canonical securities

### ISSUE THREAD

**Issue by jingwu74** [QuantConnect/Lean#1886]
#### Expected Behavior

ConstantAlphaModel should exclude canonical securities in futures and options algorithm.
#### Actual Behavior

Insights in ConstantAlphaModel for futures and options include a canonical security(the entire chain) with symbols being `/CL`.

#### Reproducing the Problem

``` csharp
namespace QuantConnect.Algorithm.CSharp
{

    public class BasicTemplateFrameworkCryptoAlgorithm : QCAlgorithmFramework
    {

        public override void Initialize()
        {
            UniverseSettings.Resolution = Resolution.Minute;

            SetStartDate(2016, 1, 1);  
            SetEndDate(2016, 1, 4);  
            SetCash(100000000);           
            DebugMode = true;

            var futureCL = AddFuture(Futures.Energies.CrudeOilWTI, Resolution.Minute);
            futureCL.SetFilter(TimeSpan.Zero, TimeSpan.FromDays(120));

            UniverseSelection = new ManualUniverseSelectionModel(Securities.Keys);
            Alpha = new ConstantAlphaModel(InsightType.Price, InsightDirection.Up, TimeSpan.FromMinutes(20), 0.025, null);
            PortfolioConstruction = new EqualWeightingPortfolioConstructionModel();
            Execution = new ImmediateExecutionModel();
            RiskManagement = new Algorithm.Framework.Risk.NullRiskManagementModel();
        }
    }
}
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
We should also inspect other models to ensure we're not doing something similar there as well.

Perhaps the root cause of this is that we emit the canonical symbols in the security changes event, which is then picked up by various framework algorithms leading then to create indicators and other 'symbol data' type of stuff. Maybe this is just something models need to be aware of? Other options to consider are removing the canonical symbols from the event, but I think that would cause more harm than good.

Anyone else have thoughts on the matter?
