### ISSUE TITLE
ExponentialWeightedMovingAverage 

### ISSUE THREAD

**Issue by marinkobabic** [QuantConnect/Lean#2005]
Do you have ExponentialWeightedMovingAverage?

**Comment by AlexCatarino** [comment]
Hi @marinkobabic, no and yes.
No, we don't have a `ExponentialWeightedMovingAverage` that you would call as:
```csharp
var ewma = new ExponentialWeightedMovingAverage(10);
```
But yes, since you have use extension method `WeightedBy`:
```csharp
var ema = new ExponentialWeightedMovingAverage(10);
var volume = new Identity("Volume");
var ewma = ema.WeightedBy(volume, 1);
``` 

If the code snippet above does not give you the indicator you are looking for, please ask for help at the [forum](https://www.quantconnect.com/forum).
