### ISSUE TITLE
Python module not found

### ISSUE THREAD

**Issue by pieroliviermarquis** [QuantConnect/Lean#2021]
I have just started to familiarize myself with LEAN and some of the python examples on Github are using these import statements or similar ones and are not working: 

```
from Portfolio.EqualWeightingPortfolioConstructionModel import EqualWeightingPortfolioConstructionModel
from Alphas.ConstantAlphaModel import ConstantAlphaModel
from Execution.ImmediateExecutionModel import ImmediateExecutionModel
from Risk.MaximumSectorExposureRiskManagementModel import MaximumSectorExposureRiskManagementModel
```

Perhaps these modules are now all imported via  `QuantConnect.Algorithm.Framework.<moduleName>`

**Comment by AlexCatarino** [comment]
Hi @pieroliviermarquis, what do you mean by "not working"?
Sometimes we need to rebuild Lean in order to the python framework modules are moved over to `Lean/bin/Debug` and be compiled when the engine imports the algorithm.

Note that we have C# and python version of the framework models/modules. The C# ones are imported via `QuantConnect.Algorithm.Framework.<moduleTypeName>` while the python ones are imported via `<moduleTypeName>.<moduleName>`. You can use either C# and python modules in python algorithms.
