### ISSUE TITLE
Python Running 1/20th Speed of C# Algorithms

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#2026]
#### Expected Behavior
Python should ideally be "near parity" with C# strategies (30% performance hit maybe). "Using" the algorithm API shouldn't create exponential decay in performance... 

#### Actual Behavior
Python algorithms take a 95% performance hit.  

#### Potential Solutions
 - Remake dedicated LEAN python stack
 - Make AlgorithmManager in Python
 - Build our own bridge to replace pythonnet
 - Use compiled version of c-python?

Creating this thread for discussion of potential solutions 

#### Reproducing the Problem
Run any python algorithm which crosses the C#-Py bridge a few times
 
#### Checklist 
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by disruptek** [comment]
I don't know much about LEAN, but I like the  idea of improving the performance of the Python side, so please take my ignorance as a given.

I did some profiling and the long and short is that the performance issues seem to be, as expected, in pythonnet.  The more you interact with the QC API, the slower your algo.  I took a look at the pythonnet code and it looks like it's written to be easy to read (and debug) but perhaps it is not designed with an eye towards performance.

To elaborate on this, I saw tests and operations in pythonnet that did not seem to be optimized to reduce surface against Python itself.  I believe pythonnet could be optimized, but I've done no proper analysis.

I can't say what the most painful bits are because I really haven't exercised much of the API in my test algo, but aside from patching upstream pythonnet, the best solution I can see would be to reduce/prevent object translation between C# and Python.

One thing that would help this effort would be a test algorithm written with an eye towards exercising the API beyond what our toys might do.  In particular, it's useful to stress both the C# side that doesn't need changing as well as the Python side that does, so we have metrics on what "real world" performance impacts a change might yield and how they figure into the overall picture of performance.

One question I have as a neophyte to LEAN, pythonnet, (and even C#) is whether QC is building their own pythonnet binaries from a custom branch.  If this is already a part of the toolchain, it puts us in a better position to experiment with low-hanging fruit in pythonnet optimizations.

Based upon my (again, **very limited**) profiling, however, I don't see real Python algorithms achieving a mere 30% hit regardless of pythonnet optimizations:

If we say an API query like `Portfolio.Invested` costs 1 unit (of time) in C#, then just getting the Python GIL costs us another unit.  The pythonnet machinery to get the boolean value into python costs about 30 units.  Evaluating the Python code itself is about 1/2 unit.  So we're dealing with a pretty big delta, here.

The best idea I have for achieving that "near parity" figure is also the easiest to implement: **slow down the C# algorithms**

But, we really need a good representative algorithm to confirm these measurements and serve as a baseline.  For all I know, a large portion of what I've profiled is JIT compilation/caching performed by pythonnet which, over the course of a few minutes, might amortize out.  Without a long-running algorithm of even modest complexity, the profiling figures above really cannot be trusted.

**Comment by jaredbroad** [comment]
Rough benchmarks of 2 years basic template algorithm on second data; -- 50% hit from doing nothing.
 - C# - `16.07 seconds at 119k data points per second. Processing total of 1,918,802 data points.`
 - Py - `32.14 seconds at 60k data points per second. Processing total of 1,918,802 data points.`

adding `if self.Portfolio.Invested: pass`

 - C# - `17.07 seconds at 112k data points per second. Processing total of 1,918,802 data points.`
 - Py - `38.15 seconds at 50k data points per second. Processing total of 1,918,802 data points.`

Opening up the data. `bar = data["SPY"]`
 - C# - `20.10 seconds at 95k data points per second. Processing total of 1,918,802 data points.`
 - Py - `89.15 seconds at 22k data points per second. Processing total of 1,918,802 data points.`

Placing an order and checking close: `bar is not None and bar.Close > 230:`
 - C# - `18.07 seconds at 106k data points per second. Processing total of 1,918,802 data points.`
 - Py - `97.16 seconds at 20k data points per second. Processing total of 1,918,802 data points.`

```
class BasicTemplateAlgorithm(QCAlgorithm):

    def Initialize(self):
        self.SetStartDate(2017,1, 1)  #Set Start Date
        self.SetEndDate(2017, 5, 1)    #Set End Date
        self.SetCash(100000)           #Set Strategy Cash 
        self.AddEquity("SPY", Resolution.Second)

    def OnData(self, data):
        
        bar = data["SPY"]
        
        if not self.Portfolio.Invested and bar is not None and bar.Close > 230:
            self.SetHoldings("SPY", 1);
```

**Comment by disruptek** [comment]
Thanks, I will plug that in and dig deeper, but in the mean time...

I just turned my `OnFrameworkData` into a noop (locally, in C#) and noticed a speed increase of 2.5-3x.  The difference is so dramatic that the profile output looks like it's from a completely different application.

Of course, I cannot reproduce this in the QC IDE.  (Please confirm in your local LEAN installation?)

Maybe we check to see if methods are re-implemented by the user before grabbing the GIL and invoking them?

And maybe we make this new framework thingy opt-in?

**Comment by disruptek** [comment]
Despite the fact that `QCAlgorithm` implements a noop for `OnFrameworkData()`, the mere fact that `AlgorithmPythonWrapper` calls it by name (the horror!) causes it to take 10% of the runtime; fully half of the runtime of `OnData()`, including the Python implementation in the algorithm itself.

Over a 6-month 1s backtest, just removing this call causes a 36k rate to jump to 50k.

The low-hanging fruit here is to make a very un-Pythonic decision to recast the managed objects passed into Python algorithms as a subclass that forgoes certain dynamic qualities of objects that Pythonistas will expect, instead granting them the performance they deserve.

**Comment by denfromufa** [comment]
@jaredbroad @disruptek @mchandschuh can you folks generate a reproducible case that is stand-alone pythonnet calls without going into the depths of quantconnect api? And if this is possible, please report it in pythonnet issue tracker. Like discussed, I'm very interested what you find here.

**Comment by disruptek** [comment]
This avenue of research seems to've hit a dead end, but I can offer that I experienced surprising difficulty just trying to extend `PyObject` so I could have it cache some attributes, etc.  I had to add a class in pythonnet just to be able to remove the protections placed on the method signatures.

I offer that effort here in case it helps someone similarly challenged:
[https://gist.github.com/disruptek/9479b99a5be24ef997270e1d93a8831e](url)

**Comment by jaredbroad** [comment]
Thanks to @Martin-Molinero 's work - #3111, #3122, #3100, #3090, #3085, #3077, #2982, #2958, #2899 -- Python is now about -20% from C# and onpar with Cython naitive speeds.
