### ISSUE TITLE
Here was a question - about the function logic - but I realized I was not correct

### ISSUE THREAD

**Issue by IlshatGaripov** [QuantConnect/Lean#2195]
Sorry I realized my question was not correct

**Comment by AlexCatarino** [comment]
@IlshatGaripov, you can contact the quantconnect team at [Slack](https://www.quantconnect.com/slack) or [support](support@quantconnect.com) before opening issues since we can give you important insights and help you realize whether there is a logic mistake in the code. Thank you for looking into `GetMaximumOrderQuantityForTargetValue`.

**Comment by IlshatGaripov** [comment]
Thank you @AlexCatarino please excuse my lack of experience I ll make sure to use the suggested chanels of contact the next time
