### ISSUE TITLE
Smoothed Moving Average Indicator

### ISSUE THREAD

**Issue by worthy7** [QuantConnect/Lean#2363]
Feature request for a Smoothed Moving Average:

The first value for the Smoothed Moving Average is calculated as a Simple Moving Average (SMA):
SUM1=SUM (CLOSE, N)
SMMA1 = SUM1/ N
The second and subsequent moving averages are calculated according to this formula:
SMMA (i) = (SUM1 – SMMA1+CLOSE (i))/ N
Where:
SUM1 – is the total sum of closing prices for N periods;
SMMA1 – is the smoothed moving average of the first bar;
SMMA (i) – is the smoothed moving average of the current bar (except the first one);
CLOSE (i) – is the current closing price;
N – is the smoothing period.

**Comment by LouisSzeto** [comment]
A lot of source suggested that it is also known as Wilder's Moving Average ([example](https://ibkrguides.com/tws/usersguidebook/technicalanalytics/wildersindicator.htm)), which we have implementation in LEAN. I've also looked into the calculation of our existing [WMA](https://github.com/QuantConnect/Lean/blob/master/Indicators/WilderMovingAverage.cs), they looked the same to me.

**Comment by giou-k** [comment]
Is there something wrong with the formula?

You say `SUM1=SUM (CLOSE, N)`, but most probably it should be as `SUM1=SUM (CLOSE(1), N)`, or even better and more clear `SUM(i)=SUM (CLOSE(i), N)`.
So when you define the `SMMA (i) = (SUM1 – SMMA1+CLOSE (i))/ N` I guess that you need the SUM(i) and not SUM(1)...

What about the `SMMA1 – is the smoothed moving average of the first bar;`? Really we need the first one? for example for SMMA(3) we need smma of the first bar(what ever "frist bar" means since we have periods) or SMMA(i-1)?

So at the end we have:

`SMMA (i) = (SUM(i) – SMMA(i-1)+CLOSE (i))/ N`

wdyt? Thanks!

**Comment by Martin-Molinero** [comment]
> A lot of source suggested that it is also known as Wilder's Moving Average ([example](https://ibkrguides.com/tws/usersguidebook/technicalanalytics/wildersindicator.htm)), which we have implementation in LEAN. I've also looked into the calculation of our existing [WMA](https://github.com/QuantConnect/Lean/blob/master/Indicators/WilderMovingAverage.cs), they looked the same to me.

Closing issue as resolved as per LS comment
