### ISSUE TITLE
PostInitialize called too early in BrokerageSetupHandler.Setup

### ISSUE THREAD

**Issue by StefanoRaggi** [QuantConnect/Lean#2507]
#### Expected Behavior
`PostInitialize` should be called when **all** securities have been added.

#### Actual Behavior
`PostInitialize` is called before fetching open orders and holdings from brokerage and some securities are being added too late.

#### Potential Solution
In `BrokerageSetupHandler.Setup`, move the `algorithm.PostInitialize` call after brokerage initialization. 

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by jaredbroad** [comment]
Step 1: Write a test with a mock brokerage with existing holdings; (complex holdings) which gets imported successfully.  Including holdings out of filter, or in asset classes not supported. 

Step 2: Watch the previous test break because of the order of post initialize. e.g. Throw because of adjusted mode data for an options holding. Throw because asset class not supported. 

Step 3: Move post initialize to properly import the majority of tests (continue failing for the bad asset class tests)
