### ISSUE TITLE
Can't place margin order if position already exists

### ISSUE THREAD

**Issue by Adalyat** [QuantConnect/Lean#3101]
#### Expected Behavior

We want to place a new margin order (whether market or limit order) on Tick and Second resolution on live brokerage trading.

#### Reproducing the Problem

This is how i can reproduce the bug.
1) Algorithm. My algorithm looks like

```
public class BitfinexCryptoAlgorithm : QCAlgorithm
{
    public override void Initialize()
    {
        SetBrokerageModel(BrokerageName.Bitfinex, AccountType.Margin);
        AddCrypto("BTCUSD", Resolution.Tick, Market.Bitfinex);
    }
    public override void OnWarmupFinished()
    {
        foreach (var item in Portfolio.CashBook)
        {
            Log($"{item.Key} : {item.Value.Amount}{item.Value.CurrencySymbol}");
        }
    }
    public bool invested { get; set; } = false;
    public override void OnData(Slice data)
    {
        if (!invested)
        {
            MarketOrder(Symbol("BTCUSD"), 0.04);
            invested = true;
        }
    }
    public override void OnOrderEvent(OrderEvent orderEvent)
    {
        Log(orderEvent.ToString());
    }
}
```

2) Assume that it's the first time when you run algo and we don't have opened orders or positions. Run algo. Success. 

![2019-04-18_19-24-42](https://user-images.githubusercontent.com/3648114/56383664-0f34b280-6223-11e9-9247-e613043b0a93.png)

Stop algorithm.
3) Run it again. Now we can see that Lean throw exception with 'price is 0' message
![2019-04-18_19-25-22](https://user-images.githubusercontent.com/3648114/56383179-ecee6500-6221-11e9-8f57-5c3a2b419ee2.png)

#### System Information

After some experiments I found that there are a few key points to reproduce the problem:
1) Marging trading only;
2) Small resolution (Tick for Bitfinex);
3) Existing positions (GetAccountHoldings should return not empty list).

Under debug I found that `PreOrderChecksImpl` check fails with exception mentioned above.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
I believe this is because `Bitfinex` `GetAccountHoldings()` implementation (at https://github.com/QuantConnect/Lean/blob/master/Brokerages/Bitfinex/BitfinexBrokerage.Utility.cs#L204) is not setting `MarketPrice` used by the `BrokerageSetupHandler` to set security prices for any existing holding (at https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BrokerageSetupHandler.cs#L336). 

Maybe `Bitfinex.GetAccountHoldings()` could call `Bitfinex.GetTick()` and set the market price as the average?

What puzzles me is that _if_ the algorithm has only 1 security, what is being sent through the `OnData` call if not a new price update (which should already have been set for the security, **meaning price shouldn't be 0**)?

Note that during live mode, with multiple securities using tick, I believe there is no guarantee all security prices will be set (unless there is an existing holding) before the first slice package is sent, due to the asynchronous nature of the ticks, my point is: checking for price != 0 might be a good idea anyway (despite this bug).

**Comment by Martin-Molinero** [comment]
Fix already implemented at https://github.com/QuantConnect/Lean/tree/bug-3101-bitfinex-getaccountholdings-set-market-price , waiting on live test validation.

**Comment by Adalyat** [comment]
@Martin-Molinero have you tried it or you want I try it on my accounts?

**Comment by Adalyat** [comment]
@Martin-Molinero I can confirm that this error has gone. Tried a multiple time on different resolutions, so could reproduce without your commit, but couldn't with it.
