### ISSUE TITLE
Update Symbol Helper to Also Parse Symbols

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#3110]
#### Expected Behavior
To facilitate better history requests the `QCA.Symbol()` method should accept "SPY" or the full encoded symbol string "SPY R735QTJ8XC9X" so users can easily decode symbol objects without knowing the details of the Parse API.

`self.ibm = self.Symbol("SPY R735QTJ8XC9X")`
`var ibm = Symbol("SPY R735QTJ8XC9X");`

#### Actual Behavior
Throws if not found in symbol cache.

#### Potential Solution
Attempt to Parse() as a full symbol hash before throwing an exception.
```
public Symbol Symbol(string ticker)
{
    return SymbolCache.GetSymbol(ticker);
} 
//SymbolCache
public static Symbol GetSymbol(string ticker)
{
    Symbol symbol;
    if (TryGetSymbol(ticker, out symbol)) return symbol;
    throw new Exception(string.Format("We were unable to locate the ticker '{0}'.", ticker));
}
```

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by StefanoRaggi** [comment]
The parsing of the symbol identifier string seems to be already implemented here:
https://github.com/QuantConnect/Lean/blob/master/Common/SymbolCache.cs#L137
These two statements have the same effect:
```
var x = Symbol("SPY");
var x = Symbol("SPY R735QTJ8XC9X");
```
the correct symbol is returned from the `SymbolCache` if the security was added previously, otherwise this exception is thrown: `We were unable to locate the ticker`, as documented here:
https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.cs#L1999

**Comment by jaredbroad** [comment]
Thank you!
