### ISSUE TITLE
The setting "plugin-directory" can't be overruled via a custom config file

### ISSUE THREAD

**Issue by uli-weltersbach** [QuantConnect/Lean#3258]
Not sure if this is a known limitation, but I couldn't find any related/closed issues, so here we go:

#### Reproducing the Problem
1. Add the following to `config.json`:
```json
"plugin-directory" : "Hello from config.json!"
```
2. Create a copy of `config.json`, named `my-config.json`.
3. Change the value of `plugin-directory` to `Hello from my-config.json!`.
4. Mark `my-config.json` as "Copy always".
5. Run e.g. a backtest, and set the active configuration file to `my-config.json` by passing `--config:my-config.json` to `QuantConnect.Lean.Launcher.exe`.

#### Expected Behavior
6. The field `PluginDirectory` in `Composer.Instance` is `Hello from my-config.json!`.

#### Actual Behavior
6. The field `PluginDirectory` in `Composer.Instance` is `Hello from config.json!`.

#### System Information
QuantConnect.Lean commit `d43344318a69ae7cc495c6d4f32aeaadfc023bba`
Windows 10

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Doggie52** [comment]
Interesting, never seen anyone use the `plugin-directory` before. This happens because the `Composer` instance is created before we load the new config such that `Config.Get("plugin-directory")` would display the new directory.

Perhaps we should only create the `Composer` instance the first time we need it, and ensure that this is after the `args` have been parsed?
