### ISSUE TITLE
Ensure Indicators Always Receive Adjusted Data

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#383]
Indicators work best with smooth, fully adjusted data. When working with Raw or SplitOnly, DividendOnly adjusted data there are discontinuous jumps which break indicators.

This can be easily fixed by converting the data which goes into the indicator update manager and ensuring the data is always the fully adjusted version of the data (and if its already adjusted, as by default, then do nothing).

**Comment by AlexCatarino** [comment]
Where should the data be adjusted (if it is not already)?
At [Algorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Indicators.cs#L1151) or [Indicator](https://github.com/QuantConnect/Lean/blob/master/Indicators/IndicatorBase.cs#L75) level?

**Comment by jaredbroad** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Ensure Indicators Always Get Adjusted Data](https://trello.com/c/8kmvOASJ/986-ensure-indicators-always-get-adjusted-data)

**Comment by mchandschuh** [comment]
Welp, I had a massive list of running comments here, that's what I get for not posting and updating.

**#lessons-learned**

1. Need to reset 'down stream' indicators (think `Of` extension)

2. Reset should happen depth first _before_ state is reset, allowing reset handlers to cache state if necessary
a. handled via `IIndicator.Resetting` event fires _before_ the reset is applied, which invokes sub-indicators into resetting (depth-first)

3. **:warning:[REQUIRES DISCUSSION]:warning:** -- sourcing data, applicable limits? Indicators can chain infinitely deep meaning it's impossible to hold all data in RAM required to get them back to speed. Perhaps initial impl focuses on  ~500 point data cache (configurable, perhaps computed via various indicators). 
a. Further, it's insufficient to maintain recent price data, a prime example is SPY second data consolidated into daily bars to create an SPY SMA_100_daily -- value is caching at consolidator level as it is a downsampling step that ultimately reduces the total recompute time (exponentially? only if nested consolidators, but even then I think it's quadratic, but I digress)...

4. Interface `IIndicatorWarmupPeriodProvider` is insufficient as it doesn't account for consolidation (think second data -> consolidate daily -> SMA20) -- this example highlights the benefits of potentially having data caches for each consolidator... their net effect is to reduce total data required to be saved. The way indicators are currently set up, they're not aware of what resolution data they receive... and this is mostly by design, since their technically signal filters in a control structure sense.

5. Component to manage histories -- initially I was thinking linearly, shove it into `SecurityCache` and make him track the last _n_ data items via `RollingWindow<BaseData>` and have _n_ be configurable based on the data type. For long running algos, a potentially better solution may involve immutable linked lists which can be shared references for indicators with the same, or similar, streams of data input (all indicators made from consolidate SPY second -> daily) -- the linked-list-ness makes addition an O(1) opp and if we're always tracking the tail, then tail removal is also an O(1) opp. It's safe to assume this data would be used for iteration,  so random access isn't as valuable in this scenario (which is what rollingwindow provides).

6. Potentially delegate work to history provider in case not all data is available locally and somehow merge those results in.

7. Application of adjusted data would need to flow  under the _same_ semantics as during regular algorithm execution, so if _other_ indiciators are dependencies, then they too need to be pulled into this update soup. Consider a ratio dependency, `ibm.Over(msft)` -- if we invalidate msft, it means we also need to re-run ibm in tandem so the over operations work properly. And since ibm is being reset, everyone downstream of ibm would need to be reset. The composites cause an inter-linking between different graphs which  necessitates pulling in seemingly unrelated indicators to the reset operation, making it more costly. This might be avoidable if indicators self-managed their own rests and local histories, but I would expect that to consume a wee bit much RAM (immutable structures could help here, but it's still a fair amount of unique data to hold, basically inputs to _every_ indicator and that number of inputs is determined by the `IIndicatorWarmupPeriod`

8. Most of the technical hurdles arise from properly managing historical data for indicators which can be arranged into arbitrary complex and _even_ cyclical graphs. I know I'm thinking _worst case_ here, but it is possible to define such an indicator graph that any price adjustment event would require the recomputation of _the entire_ indicator graph :/  we'll need to make some choices here :)

**Comment by jaredbroad** [comment]
Similar to https://github.com/QuantConnect/Lean/issues/2127 for Volatility Models

**Comment by jaredbroad** [comment]
- Create event for price discontinuities: i.e. in live trading splits cause discontinuities even if the data is adjusted.
 - Pass access to a HistoryProvider to consumers who can self-update OR 
 - In the AlgorithmManager loop have an Indicator Manager reset and re-warm up all the indicators on this event.
 - Standardize the IVolatilityModels by prefixing them with an Identity Consolidator - so they'll fit nicely into the updated pathway.

Build to work in backtesting so we can use RAW price data with adjusted price indicators. 

 - Possibly pass the price factors back as well if helps with the adjustment.

**Comment by jaredbroad** [comment]
Closing because:
 - Too many corner cases and trying to hide it from the algorithm designer will cause more issues than simply making it all explicit.
 - The consumers can model the price discontinuity by asking for Raw prices in a backtest; then handling the splits in backtesting.
 - A common use pattern with indicators will break (comparisons to raw); e.g. `if SMA(IBM)  > slice["IBM"].Close`
