### ISSUE TITLE
Add the Ability to Expire Insights

### ISSUE THREAD

**Issue by wardjm** [QuantConnect/Lean#3967]
#### Expected Behavior

Have RiskManagementModels emit flat insights or destroy active insights when appropriate. Specifically, for instance, have MaximumDrawdownPercentPerSecurity emit flat insight when security reaches max drawdown.

JB Edit: Generally; have the ability to expire insights. 

#### Actual Behavior

Currently, MaximumDrawdownPercentPerSecurity will exit the position, but if the insight still has time left on it, a new position will open.

#### Potential Solution

Emit flat insights is one option, but destroying/eliminating the insight is probably better since some PortfolioModels may not treat a Flat insight as sending the security holdings to 0.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by scolemann** [comment]
Here is a backtest that shows the issue.  A UGAZ insight is generated at 9:31 and the framework enters the position. The risk model exits the position shortly past 10am.  At 12pm we generate an insight for DGAZ.  At that point the framework enters an equal position on both DGAZ and UGAZ because the UGAZ insight has not expired.

I think the crux of the issue is that sending in additional insights for any security causes ProcessInsights to execute and it continues to use all unexpired insights, regardless of what the Risk Management Model has done.

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_2aee16dba697e01c9aafb6a4fe4343d7.html

**Comment by wardjm** [comment]
@scolemann Agreed.

**Comment by AlexCatarino** [comment]
I am a little skeptical about insights being modified by any model other than the alpha model because it will violate the separation of concerns principle. In theory, if we run several versions of the algorithm with the **same** universe selection and alpha model, but different portfolio construction, risk management, and execution models, the insights should be the **same**.

Perhaps the risk management model should be smart enough to not let a new position be opened for the security that it has sent a zero-quantity portfolio target for a given period such as until the end of the insight expiration.

**Comment by wardjm** [comment]
I think there could be an isUsed field in the Insight class that could solve the problem, but that would just make it so all the portfolio construction models have to be updated to only use unused insights. This is effectively the same as expiring them but with a lot more work.

But yeah, if there is a way to have the risk management model control whether the construction model can open positions, that would work too.

**Comment by scolemann** [comment]
@AlexCatarino I think that makes sense because in and of themselves, Insights do not determine the action that is taken on them.  They are simply information that the other models use to determine their actions.

That said, the other models need a way to communicate/know what actions have previously been taken on those insights.  In the current design insights flow into the PortfolioConstructionModel which outputs PortfolioTargets which then flow to RiskManagement for adjustment and then to Execution.  Insights go no further than the PortfolioConstructionModel.

I think for the risk management model to do as you've suggested, the insights would need to be passed into the risk management model, possibly attached to the PortfolioTarget the Insight generated.  This however assumes a 1-1 relationship between the PortfolioTarget and Insight which is probably dependent on the portfolio model (it could optionally be a collection of insights on the target).

This would allow the RiskManagementModel to track any unexpired insights that it had previously taken action on (e.g. set to zero quantity) and adjust the targets as needed.

**Comment by wardjm** [comment]
That sounds pretty good. I haven't look into the "core" of LEAN in a while (6 months!) so things are a little foggy. There may be multiple issues at play here. One is that unless the construction model explicitly tracks it, there is no way to know whether an insight has been acted upon yet. All insights are passed in when any new insight is generated. This is usually fine until an edge case shows up like the risk model closes out a position. The construction model has no idea what happened and only sees all the valid insights and will then reopen the position. Sorry if this is starting to sound a bit pedantic. So upon more consideration, isUsed probably won't work since you'd then have to adjust how most construction models work. They probably form a new portfolio from scratch every new insight rather than adding or subtracting one at a time based on the new insights.

**Comment by scolemann** [comment]
> One is that unless the construction model explicitly tracks it, there is no way to know whether an insight has been acted upon yet.

This is a great point and I think it's ok to say that the models can track insights if they need to rather than it being a requirement in the core portfolio and risk models.

**Comment by jaredbroad** [comment]
**For simplicity the following plan is accepted:**

 - Add a Cancel method to the Insight class; on calling it would reset the object CloseTimeUtc to the current algorithm time.
 - The PCM and later models use the InsightCollection class to remove the insight from weighting automatically.

The challenge is getting the current UTC to the insights, ITimeProvider.

 **Spin off Todo:** 
 - Add Insight Collection to QCAlgorithm
 - Create the empty instance on QCAlgorithm construction
 - PCM owns injecting insights;

**Comment by AlexCatarino** [comment]
We have created the Insight Manager in QCAlgorithm: Insights. This change added the ability to expire insights.
https://www.quantconnect.com/docs/v2/writing-algorithms/algorithm-framework/insight-manager
