### ISSUE TITLE
Options margin modelling

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4065]
#### Expected Behavior

- Options margin modelling is as close to reality as possible and allows usage of option strategies to reduce margin.
#### Actual Behavior

- To be reviewed
#### Potential Solution

- Review, refactor and add more tests
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
Here's my notes from researching margin requirements with a special focus on options. I've read through FINRA Rules 2360 and 4210, as well as the parts of Regulation T that concern themselves with margin with a particular focus on offsetting transactions. I know this is a long post, but I wanted it to be a complete and sufficient reference for the forthcoming development work to improve LEAN's option margin modeling.

#### FINRA: [Rule 2360: Options](https://www.finra.org/rules-guidance/rulebooks/finra-rules/2360)
FINRA Rule 2360 defines regulations specific to trading option contracts, including how holding different classes of options can offset margin requirements. The below excerpt is also accompanied by an example to illustrate how this works in practice.

##### FINRA: Rule 2360: Options - (a) Definitions
This section aims at providing key definitions used in other section and is reproduced here for completeness and to remove any ambiguity in the following definitions and discussions thereof.

> (3) Class of Options — The term "class of options" means all option contracts of the same type of option covering the same underlying security or index.
> (10) Covered — The term "covered" in respect of a short position in a call option contract means that the writer's obligation is secured by a "specific deposit" or an "escrow deposit," meeting the conditions of Rules 610(e) or 610(g), respectively, of the rules of The Options Clearing Corporation, or the writer holds in the same account as the short position, on a unit-for-unit basis, a long position either in the underlying security or in an option contract of the same class of options where the exercise price of the option contract in such long position is equal to or less than the exercise price of the option contract in such short position. The term "covered" in respect of a short position in a put option contract means that the writer holds in the same account as the short position, on a unit-for-unit basis, a long position in an option contract of the same class of options having an exercise price equal to or greater than the exercise price of the option contract in such short position.
> (30) Series of Options — The term "series of options" means all option contracts of the same class of options having the same exercise price and expiration date and which cover the same number of units of the underlying security or index.

##### FINRA: Rule 2360: Options - (3) Position Limits
> (ii) Equity Option Hedge Exemptions
> a. The following qualified hedge strategies and positions described in subparagraphs 1. through 6. below shall be exempt from the established position limits under this Rule for standardized options. Hedge strategies and positions described in subparagraphs 7. and 8. below in which one of the option components consists of a conventional option, shall be subject to a position limit of five times the established position limits contained in paragraphs (b)(3)(A)(iii)a.1. through 6. below. Hedge strategies and positions in conventional options as described in subparagraphs 1. through 6. below shall be subject to a position limit of five times the established position limits contained in paragraphs (b)(3)(A)(iii)a.1. through 6. below. Options positions limits established under this subparagraph shall be separate from limits established in other provisions of this Rule.
> 1. Where each option contract is "hedged" or "covered" by 100 shares of the underlying security or securities convertible into the underlying security, or, in the case of an adjusted option, the same number of shares represented by the adjusted contract: (a) long call and short stock; (b) short call and long stock; (c) long put and long stock; or (d) short put and short stock.
> 2. Reverse Conversions — A long call position accompanied by a short put position, where the long call expires with the short put, and the strike price of the long call and short put is equal, and where each long call and short put position is hedged with 100 shares (or other adjusted number of shares) of the underlying security or securities convertible into such underlying security.
> 3. Conversions — A short call position accompanied by a long put position where the short call expires with the long put, and the strike price of the short call and long put is equal, and where each short call and long put position is hedged with 100 shares (or other adjusted number of shares) of the underlying security or securities convertible into such underlying security.
> 4. Reverse Collars — A long call position accompanied by a short put position where the long call expires with the short put and the strike price of the long call equals or exceeds the short put and where each long call and short put position is hedged with 100 shares of the underlying security (or other adjusted number of shares). Neither side of the long call, short put position can be in-the-money at the time the position is established.
> 5. Collars — A short call position accompanied by a long put position, where the short call expires with the long put, and the strike price of the short call equals or exceeds the strike price of the long put position and where each short call and long put position is hedged with 100 shares (or other adjusted number of shares) of the underlying security or securities convertible into such underlying security. Neither side of the short call/long put position can be in-the-money at the time the position is established.
> 6. Box Spreads — A long call position accompanied by a short put position with the same strike price and a short call position accompanied by a long put position with a different strike price.
> 7. Back-to-Back Options — A listed option position hedged on a one-for-one basis with an over-the-counter (OTC) option position on the same underlying security. The strike price of the listed option position and corresponding OTC option position must be within one strike price interval of each other and no more than one expiration month apart.
> 8. For reverse conversion, conversion, reverse collar and collar strategies set forth above in subparagraphs 2., 3., 4. and 5., one of the option components can be an OTC option guaranteed or endorsed by the firm maintaining the proprietary position or carrying the customer account.

##### FINRA: Rule 2360: Options - (7) Limit on Uncovered Short Positions
> Whenever FINRA shall determine in light of current conditions in the markets for options, or in the markets for underlying securities, that there are outstanding a number of uncovered short positions in option contracts of a given class in excess of the limits established by FINRA for purposes of this subparagraph or that a percentage of outstanding short positions in option contracts of a given class are uncovered, in excess of the limits established by FINRA for purposes of this subparagraph, FINRA, upon its determination that such action is in the public interest and necessary for the protection of investors and the maintenance of a fair and orderly market in the option contracts or underlying securities, may prohibit any further opening writing transactions in option contracts of that class unless the resulting short position will be covered, and it may prohibit the uncovering of any existing covered short position in option contracts of one or more series of options of that class.

##### FINRA: Rule 2360: Options - Discussion
This intuitively makes sense, since if assigned you could exercise your long position and immediately pocket the profit. Also interesting is that there's no mention of accrual. I was initially thinking that the spread between the short and long would afford the account additional buying power, perhaps through SMA credits, but FINRA rules appear to indicate that there's a 'matching' that takes place. It's important to note here that just because Rule 2360 doesn't explicitly state that additional buying power is given to the account due to such a covered contract positions, doesn't mean that it is not. Additional buying power is still provided to the account under the normal rules of the brokerage, often based on total portfolio value. If such a covered position has a net gain then the account would be afforded additional buying power, just not through the SMA mechanism (methinks). Consider having multiple short and long positions at different strikes:

``` text
Short Calls: 100, 150, 200, 250
Long  Calls: 155, 170, 185, 220, 230
```
Since this in linear, there's a simple algorithm for performing the matching, starting with the least favorably priced short position (low for call, high for put), find the first long meeting FINRA's definition of covering, continuing  towards more favorable strikes. The end result is prioritizing contracts that have the highest financial liability if assigned, and therefore, the highest margin. requirements. Somewhat interesting to note that the short positions with the highest financial liability are also the most unlikely positions to be assigned. This is because they're further OTM than any other positions held. FINRA Rule 260 doesn't provide a mechanism for ignoring a position even if it's highly unlikely for it to be assigned.

I had expected there to be provisions related to holding opposing classes offsetting margin requirements. Consider the account holds one short PUT@100, which if assigned, the account would need to purchase the underlying from the contract holder at $100/share. I had initially expected there to be a CALL that would be suitable for offsetting the margin requirements. As I type this, it has become clear that in order for such a CALL to provide any offsetting of margin requirements it would need to be a short position, and short positions can't be used to offset other short positions since we can't control the exercise.

Regarding my including of the equity hedging exemptions for options position limits, I think the strategies defined therein provide a really good set of cases to be tested when validating the forthcoming margin requirement changes. Some of them will benefit from the margin requirement changes while others should have no impact. This is due to the offsetting of margins, per FINRA, to be done within options of the same class. This implies that a put can't offset a long, and the reason for this makes sense when you consider who has the right to invoke the contract. For example, if I write a short call then I'm obligated to sell to the contract holder. In order for me to offset, I need to have the means to sell, either holding the underlying or another contract that gives me the right to purchase at a better price. For a put to be applicable here, it would be need to be a short put, but I'm unable to force the contract holder to exercise the contract, making it worthless since I wouldn't have _control_.

#### FINRA: [Rule 4210: Margin Requirements](https://www.finra.org/rules-guidance/rulebooks/finra-rules/4210)
FINRA Rule 4210 addresses the minimum margin requirements. Individual brokerages are allowed to impose more restrictive requirements on individual assets, account or even on the whole.

##### FINRA: Rule 4210: Margin Requirements - (b) Initial Margin
> For the purpose of effecting new securities transactions and commitments, the customer shall be required to deposit margin in cash and/or securities in the account which shall be at least the greater of:
> (1) the amount specified in Regulation T, or Rules 400 through 406 of SEC Customer Margin Requirements for Security Futures, or Rules 41.42 through 41.49 under the Commodity Exchange Act ("CEA"); or
> (2) the amount specified in paragraph (c) of this Rule

##### FINRA: Rule 4210: Margin Requirements - (c) Maintenance Margin
> The margin which must be maintained in all accounts of customers, except as set forth in paragraph (e), (f) or (g) and for cash accounts subject to other provisions of this Rule, shall be as follows:
> (1) 25 percent of the current market value of all margin securities, as defined in Section 220.2 of Regulation T, except for security futures contracts, "long" in the account.
> (6) 100 percent of the current market value for each non-margin eligible equity security held "long" in the account.

##### FINRA: Rule 4210: Margin Requirements - Discussion
FINRA rules don't provide any specifics regarding the margin required for options contract. The only thing specific to options appears to be the ability to 'cover' and option. While not explicitly mentioned in Rule 4210, and almost seemingly verboten, [Regulation T 220.128](https://www.law.cornell.edu/cfr/text/12/220.128) provides a discussion on this exact topic and allows for a short position in the underlying to satisfy the margin requirements of a put and a long position to satisfy the margin requirements of a call. More generally, if securities held in the account are able to completely offset, on a unit-per-unit basis, the risk associated with being assigned, then those securities can be used as the margin deposit (see (c) below).
> (c) Rule 431 of the New York Stock Exchange requires that a creditor obtain a minimum deposit of 25 percent of the current market value of the optioned stock in connection with his issuance or guarantee of a put, and at least 30 percent in the case of a call (and that such position be “marked to the market”), but **permits a short position in the stock to serve in lieu of the required deposit in the case of a put and a long position to serve in the case of a call.** Thus, where the appropriate position is held in an account, that position may serve as the margin required by § 220.3(d)(5).

It's important to note here that when using securities as your maintenance margin, they're _unable_ to be used as the margin deposit for anything else (see (f) below). While not explicitly stated, I read this to imply that when using the underlying to offset an option contract, we must disregard any profit in the underlying, for those shares used in offsetting, when computing margin available based on unrealized profit. For example, say we hold 150 shares of AAPL that are up 10% since purchase and we write a single call of AAPL. The 10% growth in the 100 shares used to cover the call option should be disregarded when determining the margin available as they are entirely used to cover the call. The remaining 50 shares of AAPL have 10% growth and that increase in total portfolio value provides for increasing buying power/margin available.
>(f) A similar conclusion obtains under § 220.3(d)(3). That section provides, in essence, that the margin otherwise required in connection with a short sale need not be included in the account if the customer has in the account a long position in the same security. In § 220.3(g) (4), however, it is provided that “[A]ny transaction which * * * serves to permit any offsetting transaction in an account shall, to that extent, be unavailable to permit any other transaction in such account.” Thus, if a customer has, for example, a long position in a security and that long position has been used to supply the margin required in connection with a short sale of the same security, then the long position is unavailable to serve as the margin required in connection with the creditor's endorsement of a call option on such security.
