### ISSUE TITLE
AccumulativeInsightPortfolioConstructionModel refactor

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4112]
#### Expected Behavior

- AccumulativeInsightPortfolioConstructionModel increases target by percentage for each new insight
- AccumulativeInsightPortfolioConstructionModel  could inherit from EWPCM to reduce some code duplication and gain rebalancing feature
#### Actual Behavior

- Only one insight is taken into account if two insights are emitted in the same loop
- AccumulativeInsightPortfolioConstructionModel duplicates EWPCM code
#### Potential Solution

- Fix bug, refactor
#### Reproducing the Problem

```csharp
[Test]
[TestCase(Language.Python, InsightDirection.Up)]
[TestCase(Language.Python, InsightDirection.Down)]
[TestCase(Language.CSharp, InsightDirection.Up)]
[TestCase(Language.CSharp, InsightDirection.Down)]
public void InsightExpirationUndoesAccumulation(Language language, InsightDirection direction)
{
    SetPortfolioConstruction(language, _algorithm);

    // First emit long term insight
    SetUtcTime(_algorithm.Time);
    var insights = new[]
    {
        GetInsight(Symbols.SPY, direction, _algorithm.UtcTime, TimeSpan.FromMinutes(10)),
        GetInsight(Symbols.SPY, direction, _algorithm.UtcTime, TimeSpan.FromMinutes(10))
    };
    var targets = _algorithm.PortfolioConstruction.CreateTargets(_algorithm, insights).ToList();
    var expectedTargets = new List<IPortfolioTarget> { PortfolioTarget.Percent(_algorithm, Symbols.SPY, (int)direction * 1m * 2 * (decimal)DefaultPercent) };
    AssertTargets(expectedTargets, targets);

    // both insights should expire
    SetUtcTime(_algorithm.Time.AddMinutes(11));
    targets = _algorithm.PortfolioConstruction.CreateTargets(_algorithm, new Insight[0]).ToList();

    expectedTargets = new List<IPortfolioTarget> { PortfolioTarget.Percent(_algorithm, Symbols.SPY, 0) };

    AssertTargets(expectedTargets, targets);

    // we expect no target
    targets = _algorithm.PortfolioConstruction.CreateTargets(_algorithm, new Insight[0]).ToList();
    AssertTargets(new List<IPortfolioTarget>(), targets);
}
```
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by wardjm** [comment]
There is a chat on this, but I think for clarity I will spell out my concerns in the PR.

1) AccumulativeInsight PCM is not a subclass of EqualWeighting PCM. There's almost no similarity other than I used Equal as a template for what needed to be done to make a complete pull request for a PCM. Perhaps this is my fault for including semi-useless functions and naming everything the same.

2) AccumulativeInsight PCM should not have a rebalancing function as it has no sense in the context of what is happening in the portfolio. No rebalancing can or should ever be done. When a new insight is created, a new action happens. When that insight expires, a new action happens. Rebalancing will always be null. If a rebalance happens at any point, it should produce the exact same portfolio that already exists. This seems like a waste of computation.

3) If necessary for code re-use, a BasePortfolioConstructionModel class should be created containing these base functions. Then completely unique PCMs can inherit from that instead of needing to inherit from EqualWeighting PCM. This will help keep the code cleaner and more logical. Things that have no functional relationship should not be inheriting from each other just to get the code imported.

It's very possible I caused the confusion since I was learning what was going on in the LEAN code base using EWPCM, so I may have thought it convention to name things certain ways or contain certain functions when it was entirely not true. These two PCMs are very different which is what drove me to write Accumulative in the first place.

**Comment by Martin-Molinero** [comment]
Hi @wardjm,
Thanks for the review! We agree about the `BasePortfolioConstructionModel`, we have created issue https://github.com/QuantConnect/Lean/issues/4117 and we are currently working on it.
Rebalance make sense since portfolio value can change during the life of the algorithm even if the percentage of it doesn't. The output of the PCM is `IPortfolioTarget` which actually holds the target quantity. It also gives the PCM an optional control over the Alpha model behavior, since it can choose for example to rebalance daily with insights maybe created every few minutes
