### ISSUE TITLE
Update Python Libraries

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#4129]
#### Expected Behavior
Python libraries listed in DockerLeanFoundation have the newest version possible. 

#### Actual Behavior
Since the libraries' versions are fixed, they can be outdated.

#### Potential Solution
Upgrade some libraries. Users have requested for updates of:
- pyportfolioopt (> 0.5.3)
- mlfinlab (>0.5.4)
- lightgbm from version 2.2.3 to 2.3.0. 

#### System Information
QuantConnect Cloud.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Jackal08** [comment]
mlfinlab is currently on version 0.7.1 with new portfolio optimizers added and backtest statistics such as deflated and probabilistic sharpe ratios.

**Comment by adriantorrie** [comment]
When this is updated, can the [latest `mlfinlab` be installed](https://pypi.org/project/mlfinlab/#history) please, instead of pinning to `0.5.4`.

Current version at time of this comment is: `0.9.3`

It's going through a rapid release cycle, it's had 6 releases in the past month alone:
- Two `MINOR` bumps
- Four `PATCH` bumps

Happy to help out if needed, just point me in the right direction.
