### ISSUE TITLE
Refresh Dockerfile For Greater Usability

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#4176]
#### Expected Behavior
Too many people are confused with the application docker file. We could make it just have the foundation -- and a simple script to *use* that foundation ("docker run") and mount the user's code directories.

Given the confusion on the current code directory requirement maybe it's best to make the script work with relative pathing to the output of the launcher and ask for the directories.  i.e.

docker-run.sh
```
echo "Enter path to your LEAN binaries [default ./Launcher/bin/Debug]:"
read $binaries
echo "Enter path to your Data Folder [default ./Data]:"
read $datafolder
 docker run -it quantconnect/lean:foundation -v $binaries:/root/Lean -v $datafolder:/Data
```
+ docker-run.bat etc

#### Actual Behavior
Two docker files and no documentation.

#### Potential Solution
As above

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by nabeelio** [comment]
I create my own container here based on the `mono` container. It works well. It would be ideal to have a container which is available that already has Lean installed (the git clone, etc). 

My request: you can't get around a build, but it would be great if the csproj format can be updated to the .NET Core spec, which would eliminate my hack of creating a copy of the csproj locally in order to include the files needed to run the algorithm.

I haven't tried this with Python, but the base image likely can just be changed from the `mono` one I'm using to your foundation.

It's important that there's *no* local building done outside of the container, which isn't the case now. Your `docker-run` scripts should be replaced with `docker-compose` file. (also the example I'm using for myself is in the repo). It would be extremely difficult/impossible to run this on Heroku or within a K8 cluster without this.

My repo is here, along with notes: https://github.com/nabeelio/QuantConnectDockerExample

BTW, why was tagging stopped in 2017? I have to checkout a specific commit of the master branch, which is less than ideal.

**Comment by nabeelio** [comment]
I create my own container here based on the `mono` container. It works well. It would be ideal to have a container which is available that already has Lean extracted (the git clone, etc). 

My request: you can't get around a build, but it would be great if the csproj format can be updated to the .NET Core spec, which would eliminate my hack of creating a copy of the csproj locally in order to include the files needed to run the algorithm.

I haven't tried this with Python, but the base image likely can just be changed from the `mono` one I'm using to your foundation.

It's important that there's *no* local building done outside of the container, which isn't the case now. IMHO, the `docker-run` scripts should be replaced with `docker-compose` (also a stripped down example I'm using for myself is in the repo below). It would be extremely difficult/impossible to run this on Heroku or within a K8 cluster without this.

My repo is here, along with notes: https://github.com/nabeelio/QuantConnectDockerExample

I'm using a VS project with the nuget packages (thanks for that!), I want to keep the algorithms as separate from the core engine as possible. This allows that. BTW, why was tagging stopped in 2017? I have to checkout a specific commit of the master branch, which is less than ideal.

**Comment by nabeelio** [comment]
I create my own container here based on the `mono` container. It works well. It would be ideal to have a container which is available that already has Lean extracted (the git clone, etc). 

My request: you can't get around a build, but it would be great if the csproj format can be updated to the .NET Core spec, which would eliminate my hack of creating a copy of the csproj locally in order to include the files needed to run the algorithm.

I haven't tried this with Python, but the base image likely can just be changed from the `mono` one I'm using to your foundation.

It's important that there's *no* local building done outside of the container, which isn't the case now. IMHO, the `docker-run` scripts should be replaced with `docker-compose` (also a stripped down example I'm using for myself is in the repo below). It would be extremely difficult/impossible to run this on Heroku or within a K8 cluster without this. The scripts assume a build environment that is identical to the runtime environment (I've seen some notes about hosts being on CentOS while containers are on Debian). This completely eliminates that issue. My host machine OSX 10.15, and I can run everything containerized, with a startup time of about a minute, including a complete build with an updated algo script. I've organized the `Dockerfile` so that the cache for the least-modified steps does not get invalidated.

My repo is here, along with notes: https://github.com/nabeelio/QuantConnectDockerExample

I'm using a VS project with the nuget packages (thanks for that!), I want to keep the algorithms as separate from the core engine as possible. This allows that. BTW, why was tagging stopped in 2017? I have to checkout a specific commit of the master branch, which is less than ideal.

**Comment by nabeelio** [comment]
I create my own container here based on the `mono` container. It works well. It would be ideal to have a container which is available that already has Lean extracted (the git clone, etc). 

My request: you can't get around a build, but it would be great if the csproj format can be updated to the .NET Core spec, which would eliminate my hack of creating a copy of the csproj locally in order to include the files needed to run the algorithm. By default, the Core csproj files include all source-files that are found in the directory into the build.

I haven't tried this with Python, but the base image likely can just be changed from the `mono` one using your foundation.

It's extremely important that there's *no* building done outside of the container, which isn't the case now. IMHO, the `docker-run` scripts should be replaced with `docker-compose` (also a stripped down example I'm using for myself is in the repo below). It would be extremely difficult/impossible to run this on Heroku or within a K8 cluster without this. The scripts assume a build environment that is identical to the runtime environment (I've seen some notes about hosts being on CentOS while containers are on Debian). This completely eliminates that issue. My host machine is OSX 10.15, and I can run everything containerized, with a startup time of about a minute (at most), which includes a complete build with an updated algo file. I've organized the `Dockerfile` so that the cache for the least-modified steps does not get invalidated. `docker-compose` will also auto-restart any downed containers, either in case of a crash or system reboot. It's a Docker-native tool, so there's nothing to worry about users having to install separately.

I run pylivetrader in a similar way, inside of a K8 cluster, with a hot/cold standby, with docker-compose. My plan is to run QuantConnect in a similar manner (I prefer the C# type-safety but that's an aside). Without this, QC is a no-go.

My repo is here, along with notes: https://github.com/nabeelio/QuantConnectDockerExample

I'm using a VS project with the nuget packages (thanks for that!), I want to keep the algorithms as separate from the core engine as possible. This allows that. BTW, why was tagging stopped in 2017? I have to checkout a specific commit of the master branch, which is less than ideal.

**Comment by jaredbroad** [comment]
Thanks for the notes @nabeelio; I've summarized them and posted [here](https://github.com/QuantConnect/Lean/issues/4425).

Closing #4305 as superseded by #4425
