### ISSUE TITLE
Remove "data-directory"; Standardize to "data-folder" 

### ISSUE THREAD

**Issue by mw66** [QuantConnect/Lean#4342]
https://github.com/QuantConnect/Lean/blob/master/Common/Globals.cs#L42

```
            DataFolder = Config.Get("data-folder", Config.Get("data-directory", @"../../../Data/"));
```

Why we need two different key names for the same thing?

Or rename them to be something more precise, e.g. if this is intended:

"sys-data-dir"   // e.g. Data/symbol-properties/
"user-data-dir" // e.g. user downloaded stock data from yahoo

**Comment by jfweonc** [comment]
I am new to programming but I'll give it a try. 
            DataFolder = Config.Get("data-folder", Config.Get("data-directory", @"../../../Data/"));
The code snippet can be refactored is below:  
Config.Get("data-directory", @"../../../Data/") 
The reason is: 
First, "data-directory" is not in settings object. Please check below for the settings object. 
https://github.com/QuantConnect/Lean/blob/master/Configuration/Config.cs#L92
so it would return the default value, which is "../../../Data/". So we can change 
Config.Get("data-directory", @"../../../Data/")          to                "../../../Data/"
I would like to create a pull request if that's OK. 
I know I need to read documents and follow guidelines. If there is anything else needs to be done/follow, please let me know. Thanks

**Comment by jaredbroad** [comment]
- Standardize to the Globals.DataFolder - name config the same way.
 - Review QC Cloud.
