### ISSUE TITLE
Insight Period Discrepency When Given DateTime

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4507]
#### Expected Behavior

On the backtest view page, the "Period" displayed in the Insight Summary table should be the same if we pass the Insight constructor a DateTime object or a function that returns a DateTime object.

#### Actual Behavior

When passing the Expiry.EndOfMonth function to the Insight constructor, the Insight period is as we expect. However, if we evaluate the Expiry.EndOfMonth function and pass the resulting DateTime object to the Insight constructor, the period displayed is incorrect.

#### Potential Solution

Unknown.

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_9768f5d05700c9b7d215da3671084e08.html) and view the Insight Summary table. The periods are different. 

#### System Information

Windows 10. The backtest was run in the QC web terminal.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
![image](https://user-images.githubusercontent.com/2243225/219657296-0d18db94-8a4a-42fd-8efa-ab5b51696246.png)
It looks like one of the methods is returning a period based on trading days and the other is the period including weekends/holidays. 

 - Review which one is correct; 
 - Debug flawed implementation;

**Comment by AlexCatarino** [comment]
If we log `GeneratedTimeUtc`, `CloseTimeUtc` and `Period`, the values don't add up for the `DateTime` overload.

```python
        def OnInsightsGenerated(a, collection):
            for insight in collection.Insights:
                self.Log(f'Generation: {insight.GeneratedTimeUtc} Close: {insight.CloseTimeUtc} Period: {insight.Period}')

        self.InsightsGenerated += OnInsightsGenerated
```

The bug is on [Insight.cs#L581](https://github.com/QuantConnect/Lean/blob/master/Common/Algorithm/Framework/Alphas/Insight.cs#L581). `Time.GetNumberOfTradeBarsInInterval` counts trading days, so the `Insight.Period` is not using the close time provided by the algorithm. In the example above we have 28 days to expire and only 19 are trading days, so the period will be 19 days.

We don't need the `Insight.ComputePeriod` method (see [Insight.cs#L705](https://github.com/QuantConnect/Lean/blob/master/Common/Algorithm/Framework/Alphas/Insight.cs#L705)). We can use the following logic:
```csharp
public void SetPeriodAndCloseTime(Insight insight, SecurityExchangeHours exchangeHours)
{
    // Prevent close time to be defined to a date/time in closed market
    var closeTimeLocal = exchangeHours.IsOpen(CloseTimeLocal, false)
    ? CloseTimeLocal
    : exchangeHours.GetNextMarketOpen(CloseTimeLocal, false);

    insight.CloseTimeUtc = closeTimeLocal.ConvertToUtc(exchangeHours.TimeZone);

    if (insight.GeneratedTimeUtc > insight.CloseTimeUtc)
    {
        throw new ArgumentOutOfRangeException("closeTimeLocal", $"Insight closeTimeLocal must not be in the past.");
    }

    insight.Period = insight.CloseTimeUtc - insight.GeneratedTimeUtc;
}
```

which is the same logic from the [`FuncPeriodSpecification`](https://github.com/QuantConnect/Lean/blob/master/Common/Algorithm/Framework/Alphas/Insight.cs#L722).
