### ISSUE TITLE
Greeks Always 0 With BlackScholes and Integral Price Models

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4520]
#### Expected Behavior

All price models should return non-zero greek values.

#### Actual Behavior

BlachScholes and Integral models return zero-value greeks.

#### Potential Solution

Possibly an issue with QuantLib library.

#### Reproducing the Problem

View the logs of [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_56b78eff244f704a058e7cb6ef38055d.html).

#### System Information

Run in the QC web terminal. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by ikamanu** [comment]
Hi, what is the timeline for a fix? We are considering QC for a suite of projects, and will need to get greeks when using Black Scholes.  

TBH I'm quite surprised this doesn't seem to be a high priority issue.

**Comment by DerekMelchin** [comment]
Hi ikamanu,

There is not currently an ETA for this functionality.

Best,
Derek Melchin

**Comment by automaton82** [comment]
I am also surprised Black Scholes, the most common model used, can't provide the greeks for options in QC.

It's a pretty limiting problem because the greeks don't seem to ever match the brokerages or other platforms in backtest?

**Comment by Shaggleford** [comment]
The following issue, once resolved, would indirectly resolve this issue for live mode.
https://github.com/QuantConnect/Lean/issues/5289

**Comment by Jtcollins** [comment]
Any ETA on this one? This bug is a dealbreaker. I do like the QC platform but unfortunately, I'd have to look to alternatives without this.

**Comment by automaton82** [comment]
> Any way we can get this prioritized? This bug is a dealbreaker. I do like the QC platform but unfortunately, I'd have to look to alternatives without this.

I honestly just implemented it myself. Their Greeks implementation and pricing is incredibly slow. I suggest calculating it yourself, there's lot of C# and Python Black-Scholes examples out there.

**Comment by ikamanu** [comment]
Thanks @automaton82 , I have considered doing this, but I wasnt sure how viable it was. Would you mind sharing any code or resources for a custom implementation? There are many of us that would appreciate it greatly. Could share either here in the thread (ideally for others to benefit) or privately to ikamanu[at]gmail. Thanks in advance.

**Comment by Shaggleford** [comment]
The one drawback with a custom change is not being able to use the QC live servers.
My preference is that the greeks are pulled directly from the broker feed which then supports trading multiple underlyings without the limitation of warmup and so resolves the current limitations of the greek modelling. I've also suggested that to avoid differences between backtest and live, that the greeks are pre-calculated in the historical data, so that warmup is not required for backtest.
Afaik, only QC supports options algos for backtest and live, and so even with the limitations, there's nothing else out there. But if anyone is aware of alternatives, then please share.

**Comment by automaton82** [comment]
@ikamanu you can just search Black-Scholes C# or Python, there are plenty of examples online

@Shaggleford you can use a custom implementation in live mode, I certainly do. The data warm-up occurs when you start it in live mode, just as it does in back-test. So if you want to start back-testing for January 1, 2020 it will warm-up with the X days before. Not sure what the issue is?

You only need the warm-up data to calculate volatility anyways. Personally I use ROCP and STD in QC to calculate it. There's still no good way to get the risk-free rate, and I don't know how to get the dividend yield yet so I've hard-coded those for the tickers I'm interesting in.

The benefit again is that a custom implementation is much faster than QC's. I agree it would be nice if they pulled it from the broker but I don't think broker's can give historical greeks. IBKR for example uses a 100-step binary tree, but if you try BinomialCoxRossRubinstein in QC I don't think you can control the number of steps, and furthermore it exhibits the same issue as BS (greeks are 0).

Best to implement it yourself.

**Comment by Shaggleford** [comment]
@automaton82 I didn't think it was possible to deploy to the QC live servers if you're using a custom Lean implementation as the live nodes will be running the QC core Lean? Or is your custom implementation at the user algo level and not at the Lean level?
Agree that IBKR doesn't provide historical greeks, but it's possible to get pre-calculated Greeks in historical data - QC were looking at this possibility at one stage. The alternative is that QC does some post-processing on the current historical data to generate the greeks so that it doesn't need to be calculated on the fly.
I will definitely be rolling my own if there is no progress from QC.

**Comment by automaton82** [comment]
@Shaggleford it's at the user level. I just implemented BS and Binomial in separate classes in my project that would work with any quant platform, not just QC. Then I feed it the data in the OnData method to calculated it for that tick for that option.
