### ISSUE TITLE
GBPJPY currency conversion data feed not resolved

### ISSUE THREAD

**Issue by devalkeralia** [QuantConnect/Lean#453]
GBPJPY: requires JPY to have a non-zero conversion rate. This can be caused by lack of data.

**Comment by mchandschuh** [comment]
This happens when LEAN can't locate GBPJPY data, which it needs as a
conversion feed in order to value holdings in units of the account
currency. What's your account currency? Do you have GBPJPY data?

-Michael
On Jul 5, 2016 7:12 PM, "devalkeralia" <notifications@github.com> wrote:

GBPJPY: requires JPY to have a non-zero conversion rate. This can be caused
by lack of data.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/QuantConnect/Lean/issues/453>, or mute the thread
<https://github.com/notifications/unsubscribe/AAgb2AdGP7fbc9NaaI07zN2sERb_pyUmks5qSuTAgaJpZM4JFnez>
.

**Comment by jaredbroad** [comment]
It is actually broken, previously the default quote currency was forcibly
set to the cash currency; now with the updated symbol properties database
having lots sizes it uses the real GBPUSD USD quote currency - and the the
security never gets created because the symbol properties quote currency
isnt equal to the symbol value quote currency and then it throws these
errors! Deval and I were tracing it through this afternoon

Not sure on the fix! Suggestions welcome

**Comment by jaredbroad** [comment]
Fixed by commit 184f799
