### ISSUE TITLE
Daily chart data in BacktestResultPacket begin one day before PeriodStart

### ISSUE THREAD

**Issue by MoreDough** [QuantConnect/Lean#458]
Daily chart data for series "Benchmark" and "Daily Performance", but not for "Equity", begin one day before PeriodStart when all timestamps are adjusted -5h from UTC to America/New_York.

Chart data for "Benchmark" and "Daily Performance" seem to fit data in Spy.csv, but starts one day before PeriodStart. The difference between the series is because in AlgorithmManager.Run() "Benchmark" and "Daily Performance" are sampled with _previousTime.Date() and "Equity" with _previousTime (including time 05:00:00). 

This is probably related to Issue #460 with data for series "Equity" shifted one day forward.

To replicate this error: run local backtest with BasicTemplateAlgorithm and in method LeanWinForms.MessagingOnBacktestResultEvent() create a data dump after 
first line "if (packet.Progress != 1) return;"

The data dump can use the following code to adjust from UTC to America/New_York:
var tz = DateTimeZoneProviders.Tzdb["America/New_York"];
var localTimeKeeper = new LocalTimeKeeper(DateTime.UtcNow, tz);
var timestampAsDt = Time.UnixTimeStampToDateTime(timestamp);
localTimeKeeper.UpdateTime(timestampAsDt);
var timestampAdjustedToNewYorkTime = localTimeKeeper.LocalTime;

(Let me know if you need the dump code)

**Comment by MoreDough** [comment]
Jared, whether the bugs in issues #459, #460 and #461 that you just closed immediately is caused by the same error that causes the bug in this issue, or if it is something else is causing the other bugs doesn't really matter as long as all these bugs get corrected.

I am looking forward to the bugfix.

**Comment by jaredbroad** [comment]
Not sure its a bug @MoreDough - 

Benchmark and daily performance are daily - so don't have time, correct. There's no need for more detail for these as their primary purpose is for the statistics library which doesn't even care about the time - its just a series of points.

To answer your question though - the algorithm start and end dates are converted to UTC when you call SetStartDate/SetEndDate, and by default the algorithm timezone is EST. Can you try setting your algorithm timezone to GMT see if it helps your case?

"_"Equity" with previousTime (including time 05:00:00)._" - this is probably because the daily data has a starting time of midnight, and the market-hours-database for the symbol you're running is in EST. This would mean when its converted to GMT its +5 from midnight -> 5am tomorrow. There is nothing wrong with this as all the charting points are done in GMT -- so 0500 is correct I think?

It is strange though that Benchmark/DailyPerformance _previousDate is showing up as yesterday. It should be algorithm.StartDate -> as its initialized at the top of the loop.

**Comment by MoreDough** [comment]
1. I should mention that I have only tested with daily data. Have no ide what problems lurk in chart data with finer resolutions.

2. All data in Results.Charts should be adjusted for timezone in the same way, i.e. the same offset applied to all series should produce correct exchange time. Otherwise charting data will be very difficult to use. 

3. When I apply the same offset to all series, the series Benchmark/DailyPerformance get timestamp with correct date and the data seems to synchronize with datafile spy.csv. For example the date UTC 2016-07-07 00:00:00 (_previousTime.Date) gets adjusted to NY 2016-07-06 19:00:00, which is correct date but a ridiculous time. But time doesn't matter for daily data when drawing a chart.

However, series Equity gets adjusted from UTC 2016-07-07 05:00:00 to 2016-07-07 00:00:00 which is not the same date as for Benchmark/DailyPerformance. This is definitely a bug if I ever saw one!

I am on tz GMT +1 (+2 right now with DST). I don't see how this could cause this problem. And even if it did, it would still be a bug and is something that has to be corrected. Right?


I am attaching the dumpfile and the dump code so you can have a look for your self:
[LeanChartsDump.txt](https://github.com/QuantConnect/Lean/files/353119/LeanChartsDump.txt)
[LeanDataDumper.zip](https://github.com/QuantConnect/Lean/files/353120/LeanDataDumper.zip)

**Comment by MoreDough** [comment]
After having thought about this, I still think you have multiple bugs here and should reactivate some of the issues you closed above.

The problem with Benchmark/DailyPerformance and Equity showing two dates for the same line in spy.csv is easy to explain. Lean uses UTC for time internally. When you do _previousTime.Date, that is no longer an UTC time, but a date derived from what once was a UTC time. Right? 
So now Lean works internally with UTC and some other kind of time/date/whatever thingy in parallell. That's why you get this problem.

In order to never run into timezone confusion again,  I think a very strict principle is required that is observed everywhere in Lean and by everyone working on Lean code, without exception.

I will try to write down what I think the principle should be, and will get back to you on this shortly.

**Comment by jaredbroad** [comment]
Closed in PR #518
