### ISSUE TITLE
run_docker.sh returns error, requires config.json to exist. This file is in .gitignore

### ISSUE THREAD

**Issue by cottrell** [QuantConnect/Lean#4592]
Launcher/bin/Debug/config.json does not exist

Adding the directory allows the script to continue. 

If this run_docker.sh is only runnable after the build steps, then that should also be in a Makefile or similar. 

SUGGESTIONS/FEEDBACK:

This is a suggestion from someone who *wants* to be a user. Feel free to drop feedback but realize you are repelling and I would suggest you repel more explicitly in the project README.md and docs to save everyone's time.

All projects should either:

a) Immediately REPEL users saying this project is not for you. Don't come here.
b) have a single entry point Makefile, or similar, with clear setup steps. The readme is pretty scattered. I'm tried to run some of the install and build steps for mono but it is not at all clear what is required to simply check it out.

It looks like a lot of work has gone into getting this platform runnable across three OS which is no small feat. I'm guessing the initial setup is not run very often so is not heavily used, scripted etc. 

I just tried most of the mono and build setup on Ubuntu 20.04 and it seemed to work. This really can be put in a Makefile with comments. And it will be clearer what is intended.

**Comment by Martin-Molinero** [comment]
Hey @cottrell!
Sorry about that. A couple of days ago we merged a PR (https://github.com/QuantConnect/Lean/pull/4576) adding new readmes, including IDE integrations for debugging and developing using the Lean docker images. We also modified the scripts so they use the config at `/Launcher/config.json` so no building will be required and should run out of the box (except for C# which requires a compiled algo).
I'll close this issue since I believe mentioned PR addressed it, let us know your thoughts and what's your experience with the new updates scripts/readmes.
