### ISSUE TITLE
Add a Data Normalization Parameter to the History Method

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#4882]
#### Expected Behavior

The History method accepts a data normalization argument.

#### Actual Behavior

The History method doesn't accept a data normalization argument.

#### Potential Solution

Add a data normalization parameter to the History method.

#### Reproducing the Problem

Pass a data normalization argument to the History method. See [this related thread](https://www.quantconnect.com/forum/discussion/2604/using-datanormalizationmode-raw-and-history/p1/comment-26310).

#### System Information

QC web terminal. Firefox. Windows 10.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by SimDoes** [comment]
+1
Making a history request will always return adjusted data even though DataNormalizationMode is set to Raw (from my experience)

**Comment by jeffaxup** [comment]
It looks like this issue has not been addressed yet?
I am trying to track Historical High (52-wk-high) across split events. My main alg uses 'raw', but I need 'adjusted' for the history function to get the correct historical high value.
+1 to add this feature soon.
While you're at it, maybe adding a standard Get_52_wk_high() function would be nice, which defaults to adjusted values, so that we don't have to hand-craft this out of the history function each time.
