### ISSUE TITLE
Trading engine does not reduce the quantity of assets after placing order in live trading mode

### ISSUE THREAD

**Issue by borseno** [QuantConnect/Lean#4906]
#### Expected Behavior
After order is placed ("Filled") in a brokerage in live mode, Portfolio.Cashbook[Currency] is reduced until the order is canceled or completed

#### Actual Behavior
After order is placed, Portfolio.Cashbook[Currency] retains the same value, which causes algorithm script to work incorrectly (it has out-of-date data).

#### Potential Solution
Maybe add some plumbing to reduce it automatically so that algorithm script doesn't have to call Update() on portfolio manually?

#### Reproducing the Problem
1. Take this algo: 
[script.txt](https://github.com/QuantConnect/Lean/files/5473274/script.txt)
2. Setup the needed configuration (check for config.get occurrences in the script)
3. Get some base + quote amounts on your account
4. Run the algorithm
5. After sell / buy order has been filled on the exchange, the amounts are not subtracted

#### Checklist

- [x] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch - **By using Binance broker**
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

#### Update
I have my own brokerage that I'm using, currently it does not support completed order websocket, and that's of course an issue on my side most probably, but anyway even if an order was not completed yet, the engine still may want to update the portfolio to not include the amount of funds placed and not closed yet.

I have checked Binance brokerage and it did reduce amount of funds in portfolio after an asset was sold / bought, however I believe that's because Binance sent some private order event message? 

Anyway later even with Binance broker which is on master after placing appx. 5-6 trades with the algorithm I provided, starting with 127 USDT and ~0 BTC, now I have "-114" USDT and (the hell? ) 241 worth of USD BTC.
![image](https://user-images.githubusercontent.com/33373431/97845982-ff41ce00-1cf5-11eb-967d-67fa09335a7b.png)

Can you please let me know about the above? How should I manipulate the Portfolio from my Brokerage so that it works with Lean properly? Also even if I don't manipulate why doesn't it reduce the values after an order was placed? It should. Binance also doesn't seem to work with this properly.

I don't mind fixing Binance also beyond my broker that I'll integrate soon. But can you please comment on the above and let me know how can we fix this portfolio manipulation? What notifications / messages do I need to send to Lean regarding order results / statuses?

**Comment by BadgerTheAdger** [comment]
Ok I have debbuged through / I verified that the issue is indeed about Lean, maybe it's not an issue but a "feature", but I still want to clarify something... The amount sold is reduced + the amount bought is indeed modified in the "ProcessFill" method which is the same as saying "Process completed order". But until it's completed, my algorithm will have incorrect amount of funds there. ![image](https://user-images.githubusercontent.com/33373431/97882260-16031780-1d2c-11eb-91eb-44d27b992c4c.png)

Let's say I have 100 USDT. I have placed a request to sell 50. So right now I have 50 on hold and 50 free. My algorithm still thinks it's 100 free until the order is completed.

**Comment by Martin-Molinero** [comment]
Hey @BadgerTheAdger,
Partially filled and filled order events emitted by the brokerage will be taken by the `BrokerageTransactionHandler` at https://github.com/QuantConnect/Lean/blob/master/Engine/TransactionHandlers/BrokerageTransactionHandler.cs#L993 and sent to the portfolio to handle the update before letting the algorithm now
>  How should I manipulate the Portfolio from my Brokerage so that it works with Lean properly?

The brokerage should be emitting OrderEvents not manipulating the Portfolio directly, suggest you follow existing brokerages implementations as a guide.

**Comment by BadgerTheAdger** [comment]
Hello @Martin-Molinero ,

Thanks for the answer. 

How about reducing funds that are on hold also? 
Also try to reproduce the second problem I identified with Binance broker (it was telling me that I had ~200+ $ worth of BTC and -100 $ worth of USD after a couple of trades have been made (basically just selling/buying same asset you can take a look at the algo))

**Comment by BadgerTheAdger** [comment]
Hello @Martin-Molinero ,

I think I have found the solution to the issue I just described!

Do I understand it correctly that the brokerage has to **negate** the amount when it's a SELL?

Based on this code below, see it's subtracting amount from quote and adding amount to base. 
![image](https://user-images.githubusercontent.com/33373431/98026959-9604ac80-1e14-11eb-82f7-11a10fd1b0a8.png)

Because Lean has a reverted logic ("buy" means buying base instead of buying quote as it is normally) - looks like it's correct for "buy" but incorrect for "sell" if I don't revert the value from brokerage. (I'm using binance broker for examples but looks like it's not fully tested and there are some concerns there). 

So do I need to revert the amount for the SELL order events?
