### ISSUE TITLE
Upgrade Mono to 6.10.0.104

### ISSUE THREAD

**Issue by kgoderis** [QuantConnect/Lean#4938]
An upgrade of Mono is required to make C# libraries like TensorFlow.NET and NumSharp work. With the current version of Mono the Mono runtime crashes when NumSharp makes unprotected memory allocations

The upgrade is simple, e.g. change the release number in DockerfileLeanFoundation

#### Checklist
- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Hey @kgoderis!
Thanks for the report. We've tested new versions of mono before and we've seen issues with explosions/hanging, that's why we've stick with mono 5.12 for now and haven't really hit a blocking issue.
> With the current version of Mono the Mono runtime crashes when NumSharp makes unprotected memory allocations

Maybe you can share more details on this: logs/stack/how to reproduce/system info/etc. You've seen the issue get fixed with mono 6.10?

**Comment by kgoderis** [comment]
@Martin-Molinero Some bits can be found at https://github.com/SciSharp/NumSharp/issues/430 but when I re-created the container with the most recent Mono the problem went away, but that being said, I did not run the unit tests of the repo, so no 100% assurance that this upgrade does not break anything

**Comment by jaredbroad** [comment]
Thank you for the testing @kgoderis Our next upgrade will likely be .NET core/5.0 in the next month or two. Hopefully, we can skip over further mono upgrades.
