### ISSUE TITLE
Research Project Doesn't Include Requirements for QuantBook

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#4956]
#### Expected Behavior

There is a Requirements.txt containing all the python packages needed to run a QuantBook in Jupyter lab.

#### Actual Behavior

No such file exists

#### Potential Solution

Add all the required files to a txt file and include info on it in the ReadMe

#### Reproducing the Problem

N/A

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Martin-Molinero** [comment]
Not 100% sure about having _separate_ requirements just for research, because the requirements should be the same as those at https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#running-lean-locally-with-python which is already a documented requirement for running research locally https://github.com/QuantConnect/Lean/tree/master/Research#running-jupyter-locally?

**Comment by C-SELLERS** [comment]
Ah true, I see that it does point you to the Python install. Fair enough 😄
