### ISSUE TITLE
Test Helper to Run Example Algorithms

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#53]
Create test helper which runs through all example algorithms included in Lean. As we add new features write an example algorithm for each feature. The test helper will make sure the full system continues to work going forward.

**Comment by ammachado** [comment]
How that would happen? I mean, for each example algorithm the Engine.Main method would be called using the algorithm?  If not, can you guys provide some sample code on how to do it?

Another thing, how about move the example algorithms to its own DLL?

**Comment by mchandschuh** [comment]
I think the spirit of this issue is to create a test runner capable of running a 'specific' algorithm. It shouldn't have to be in the /Examples folder.

I have considered moving the /Examples folder into its own dll, but currently we look for QuantConnect.Algorithm.dll, so changing what dll is to be loaded wouldn't be as trivial and would probably end up with requiring extra configuration (assembly qualified name instead of just type name).

**Comment by mchandschuh** [comment]
This has been implemented in the AlgorithmRunner class in QuantConnect.Tests project.
