### ISSUE TITLE
Code to install mono=5.12 does not work

### ISSUE THREAD

**Issue by hn2** [QuantConnect/Lean#5304]
I tried many times to install mono 5.12 but it keeps installing the latest version only
One error that I'm getting:
Conflicting distribution: http://download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.12.0.226 InRelease (expected stable-xenial/snapshots/5.12.0.226 but got xenial)

**Comment by Martin-Molinero** [comment]
Hey @hn2! I remember having to play with `apt-cache policy mono-complete` & `aptitude install mono-complete` to get it using the right version. Suggest using existing docker images at https://hub.docker.com/repository/docker/quantconnect/lean see `quantconnect/lean:foundation`
Closing since it's not a Lean issue.

**Comment by hn2** [comment]
Can you please post the correct code to install mono? The code on LEAN main page does not work.
