### ISSUE TITLE
Zero Total Portfolio Value After Initialization in Crypto

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5439]
#### Expected Behavior
`TotalPortfolioValue` should not be zero if the algorithm is initialized with account currency is has a value of zero.

#### Actual Behavior
The algorithm stops with
`AlgorithmManager.Run(): Portfolio value is less than or equal to zero, stopping algorithm.`
even if we have crypto-currencies in the cashbook.

#### Reproducing the Problem
```csharp
namespace QuantConnect.Algorithm.CSharp {
    public class UpgradedBlueFish : QCAlgorithm {
        public override void Initialize() {
	        SetStartDate(2015,1,24);
        	SetCash("USD", 0);
        	SetCash("BTC", 10); 
        	AddCrypto("BTCUSD");
        }
    }
}
```
#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is due to there being no data to get the conversion rates from, it's requesting a 10-minute data window and getting no data because there isn't any for it. See https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BaseSetupHandler.cs#L81

In this case, I think it could log an error and try to fall back to a daily resolution history request if it used a higher resolution one
