### ISSUE TITLE
readme.md :: debian instruction to old and not good

### ISSUE THREAD

**Issue by m9tz** [QuantConnect/Lean#5468]
Hi guys -- thanks for the work -- but:

that you want a python 3.6 -- ok noproblem with conda!
but you write: "current version of Ubuntu - 17.10" -- hmm the readme.md was updated 3 mounth ago?
so I doubt why should I install "mono" from 

download.mono-project.com/repo/ubuntu stable-xenial/snapshots/5.12.0.226

this 16.04 lts ? are you sure you need this version? I think mono-version 6.12 is insinde everywhere? 
I'am using debian testing so I try the debian 10 (buster) way for debian 11

**Comment by Martin-Molinero** [comment]
Hey @m9tz!
We've tested new versions of mono and they seem to work _most_ of the time (we've seen a few bugs), but not as consistent as 5.12 so we've continued using it instead and we will probably no longer update mono since we are coming close to finishing the net5 migration of Lean ✨ see https://github.com/QuantConnect/Lean/issues/452.

We usually suggest directly using the QC docker images so no setup is required (docker files at https://github.com/QuantConnect/Lean). Also, suggest checking out https://github.com/QuantConnect/lean-cli a new awesome CLI we've been working on
