### ISSUE TITLE
Bitfinex Fee Discount to Fill Quantity Results in Quantity That Does Not Obey Lot Size

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5561]
#### Expected Behavior
The quantity of a position should have the same decimal places of the lot size.

#### Actual Behavior
In Bitfinex brokerage model, the executed amount is subtracted by the fee, since the fee may not respect the same lot size, the final fee quantity will have different decimal places. E.g:

Buy 1 NEOUSD (Lot size: 0.00000001)
1st fill: executed amount -> 0.23826819, fee -> 0.0484018001166,
    fill quantity -> 0.23826819 - 0.04840180**01166** = 0.18986638**98834**
2nd fill: executed amount ->  0.76173181, fee -> 0.1547534345196
    fill quantity -> 0.76173181 - 0.15475343**45196** = 0.60697837**54804**
0.23826819 + 0.76173181 = 1

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
Closing this after the work done in #5600

Summary of findings:
FeeModel is correct in not rounding the resulting BTC because Bitfinex does not round when applying the fee. This does mean that we may have holdings that are under the lot size, but this does not cause issues with sell orders as Lean will adjust to proper lot size before letting orders go through.
