### ISSUE TITLE
Visual Studio Build errors:

### ISSUE THREAD

**Issue by AliSeraji** [QuantConnect/Lean#5616]
When I simply build the code there are 26 errors :
1-'as' requires Python 2.6 or later while I have python 3.9 installed
2-Severity	Code	Description	Project	File	Line	Suppression State
Error		Your project does not reference ".NETFramework,Version=v4.0" framework. Add a reference to ".NETFramework,Version=v4.0" in the "TargetFrameworks" property of your project file and then re-run NuGet restore.	QuantConnect.Algorithm.PythonTools	D:\VISUALSTUDIO\MSBuild\Microsoft\NuGet\16.0\Microsoft.NuGet.targets	186	

I already have that target version.

3-Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3644	The reference assemblies for .NETFramework,Version=v5.0 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks	QuantConnect.Tests	D:\VISUALSTUDIO\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	1175	

when I install it then some project files can't be loaded.

Any suggestion?

Thanks in advance.

**Comment by Martin-Molinero** [comment]
Hey @AliSeraji!
We recommend using the [LEAN CLI](https://www.quantconnect.com/cli) as a tool for developing locally, since we can't provider support for NxM different dev environments.

- Python installation guide at https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python
- dotnet 5 has to be installed locally

I also get the following error locally, we will try to see it removed, but it causes no real issues, Lean still can build and run successfully. 
![image](https://user-images.githubusercontent.com/18473240/120344422-f20eb100-c2cf-11eb-8c33-77d00682802a.png)

Closing issue for now
