### ISSUE TITLE
Can't Trade Options on BRK.B Even Though the Data Is In Place

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#5636]
#### Expected Behavior

We can trade options for securities that we have option data for.

#### Actual Behavior

In [this project](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_631d8c78dfe4b25aca9306516807ebd3.html), the notebook shows the data is in place, but it's not being attached to slice.OptionChains during a backtest. This is not the case when we replace BRKB with TSLA in the algorithm.
 It's strange because upon completion of the backtest, the algorithm logs

> completed in 1.10 seconds at 44k data points per second. Processing total of 48,771 data points.

so we know some data is being processed.

Additionally, [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_fb0a03b63a0b45af0aa1cff959fe21a8.html) shows that when we try to buy an option for BRK.B after adding it with the `OptionChainProvider`, we get 

> Backtest
 Handled Error: BRKB  220121P00210000: The security does not have an
accurate price as it has not yet received a bar of data. Before placing a
 trade (or using SetHoldings) warm up your algorithm with SetWarmup, or
use slice.Contains(symbol) to confirm the Slice object has price before
using the data. Data does not necessarily all arrive at the same time so
 your algorithm should confirm the data is ready before using it. In
live trading this can mean you do not have an active subscription to the
 asset class you're trying to trade. If using custom data make sure
you've set the 'Value' property

Although, this error isn't thrown when we run the same algorithm with TSLA instead of BRK.B.

#### Potential Solution

N/A

#### Reproducing the Problem

Run the backtest above.

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by C-SELLERS** [comment]
This seems to be two problems playing into one,

The reason in research we are able to get these values is specifically because you are using "BRKB" as the ticker when adding the option. Then when you use `GetOptionHistory`, it hasn't updated that ticker to be what it is today "BRK.B"(bug 1) , "luckily" for this case our data on the other end is under "BRKB" (bug 2). So it successfully retrieves open interest data which is all you need for the history request to print out the contracts.

But when it actually goes to collect the option quote and trade bar data, it does get updated to be "BRK.B" by a map resolver. Then when we go to retrieve it, the data cannot be found under "BRK.B" because of bug 2. 

This is all from local testing, so it is possible that cloud backend for data file resolving acts differently, but the issue does seem to be something that could occur.

**Comment by C-SELLERS** [comment]
Did some further testing with research to prove my point, even weirder is that if you use BRK.B, it *can* still resolve the data for the history request somehow. Wondering if that is the cloud implementation 🤔 

But to prove that BRK.B vs BRKB does affect the contract list lookup I used the following cells

Same base cell: (swap out BRKB and BRK.B)
```
self = QuantBook()

option = self.AddOption("BRKB", Resolution.Minute)
option.SetFilter(-3, +3, 0, 31) 
```

then run 
```
time =  datetime(2019, 1, 15)
list = self.OptionChainProvider.GetOptionContractList(option.Symbol.Underlying, time)
```

This `GetOptionContractList` is the offender that uses without mapping and is what is used underneath `GetOptionHistory()`

The result after using this shows the using "BRKB" returns a ton of contracts, and "BRK.B" returns none.

**Comment by MatteMatto** [comment]
@C-SELLERS Was Option Chain Provider Symbol Map Resolve #5664 intended to fix this issue?

**Comment by AlexCatarino** [comment]
Data issue:
https://www.quantconnect.com/forum/discussion/16125/brk-b-minute-the-issue-starts-from-jan-1st-2013-12-00-am-and-continues-until-now/p1
