### ISSUE TITLE
Bug: LOGR method throws ArgumentException

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#565]
The detailed error is `System.ArgumentException: Type mismatch found between consolidator and indicator for symbol: AAPL.Consolidator outputs type TradeBar but indicator expects input type IndicatorDataPoint`.

Seems the problem has to do with the `RegisterIndicator` overloading because [`LOGR`](https://github.com/QuantConnect/Lean/blob/master/Algorithm/QCAlgorithm.Indicators.cs#L566) calls the `RegisterIndicator` like this:
```cs
RegisterIndicator(symbol, logr, resolution);
```
I'm not sure why, but if you change the `RegisterIndicator` call to:
```cs
Func<BaseData, decimal> selector = null;
RegisterIndicator(symbol, logr, resolution, selector);
```
it works fine.

**Comment by mchandschuh** [comment]
This is an inherent issue with optional parameters and overloads. It's hard
to tell for sure (without tool support) which method the compiler will
choose. Most indicator methods accept the selector as an optional argument
which would fix the issue, since the selector would be the deciding factor
in the method resolution.

**Comment by mchandschuh** [comment]
I think the real solution here is to accept an options `Func<BaseData, decimal> selector` like the other indicator helper methods do. As a general rule, all one dimensional indicator helpers (indicators that operate only on `IndicatorDataPoint` should accept a `Func<BaseData, decimal> selector` that defaults to `null` in the helper method. This would preclude the method ambiguity discussed.

Multi-dimensional indicators, such as those accepting `TradeBar` should have a `Func<BaseData, TradeBar> selector` which also defaults to null (if I recall correctly), this would allow a user project the data into a trade bar if desired (think custom type -> `TradeBarIndicator`)

**Comment by mchandschuh** [comment]
One more tid-bit here to answer @Jay-Jay-D's question directly. The reason it happens is because one of the methods is generic on `IndicatorBase<T>` while the other is non-generic and accepts IndicatorBase<IndicatorDataPoint>, so by not specifying the `selector` the compiler isn't really sure which one to go with, and goes with the one it thinks fits best, which in the case above, it chose to correct one from a compilation standpoint, but the wrong one from an 'intent' standpoint.

**Comment by Jay-Jay-D** [comment]
I fix the problem adding an optional selector in the helper method #569.
