### ISSUE TITLE
Create IOptimizer Interface in QCAlgorithm

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#578]
Allow users to set the optimization technique to use. Set the IOptimizer which will generate the parameter sets to backtest. 

IOptimizer would take in the last set of results; and return a new parameter set to backtest over.

E.g. A "GridSearchOptimization" would be called once with no results at the start; then it would return linear steps across each of the parameter variations to make up all possible combinations to backtest. A GenericOptimizer would remember breed its parameter sets as to get the best results and generate new ones. Bisect optimizer could bisect and skip large empty parts

The optimizer would be stateful; so could record result sets to perform searches over all results before returning the new parameter set.

**Comment by fbertram** [comment]
I poked a bit around in the code and am planning to do some coding on Thursday and Friday. Here are my current thoughts:

1) I'd like to extend ParameterAttribute to also hold value ranges for parameters. This way, an algorithm not only publishes its parameters, but also their valid ranges. I feel strongly about this. In addition, I'd like to have 'parameter groups'. Only parameters in the same group will be optimized concurrently and effectively multiply the size of the parameter space. Different groups will optimize sequentially. Regardless of the optimizer type (grid, genetic, other), this has the potential to greatly reduce the parameter space.

2) I was thinking to derive the optimizer classes from IJobQueueHandler. This way, an optimizer can be instantiated just like an algorithm. Unlike the current job queues, the optimizer would return a new job (or null) for every new parameter set. This will force minor changes in the current job handlers, as these would need to return null for the second and following calls.

3) to make (2) work, the launcher would need to be modified. Mostly, it will contain a while (leanEngineSystemHandlers.JobQueue.NextJob(...)), instead of just going through things just once.

4) so far, it seems that the engine will create a new thread to run each job in. If not, there is a bit of work required to make sure the jobs are running in parallel to the launcher.

5) a mechanism to feed results back into the job queue is needed. This is required under all circumstances: all optimizers needs to know when jobs are finished to limit the number of concurrent threads to a reasonable number; this will happen by blocking the NextJob call until a new slot is available. In addition, genetic optimizers needs to know the results of previous populations in order to make choices for the next generation. I am not 100% sure how this will look like, yet.

6) the optimizer needs to dump it's results. This could happen in a Shutdown method added to the job queue interface. For symmetry reasons, this would probably also call for an Initialize method... not sure what we would use that for, but maybe this helps in setting up initial populations.

It seems your ideas were slightly different and some of this might be more clear, once I am able to share some code.

Any comments welcome!

**Comment by espirulina** [comment]
Hi Bertram

   I started the Optimizer console app project.
   Right now is optimizing with a RandomOptimizer

[https://github.com/espirulina/Lean/tree/optimization/Optimizer](https://github.com/espirulina/Lean/tree/optimization/Optimizer)
   Folder /Optimizers/ contains already the GenericOptimizer, and the othe specific Optimizers classes.
   GenericOptimizer implements IOptimizer interface
   QCAlgorithm has an IOptimizer has member.

   Ill be out for few days, but would be nice to see your progress. Fell free to slack me for collaboration or brainstorm.

**Comment by espirulina** [comment]
Hi guys, i updated my branch with **_IFitnessFunction_** interface for evaluating results.
Also changed the code, in order fot **_RandomOptimizer_** to call **_RandomFitnessFunction_**.

[Hi guys, i updated my branch with **_IFitnessFunction_** interface for evaluating results.
Also changed the code, in order fot **_RandomOptimizer_** to call R**_andomFitnessFunction_**.

https://github.com/espirulina/Lean/tree/optimization/Optimizer](https://github.com/espirulina/Lean/tree/optimization/Optimizer)

**Comment by jameschch** [comment]
I'm taking an interest in this area and ran into the old repo that integrated LEAN with GAF for genetic optimization. I have made a few fixes and cleaned up the code a little and my fork can now produce useful optimizations: [https://github.com/jameschch/LeanOptimization](https://github.com/jameschch/LeanOptimization)

This code is not intended for submission to this project, but might provide some food for thought. This repo unnecessarily implements it's own launcher and so instantiates objects and services on each run. It does not have any support for parallelism but has the potential to use the grid capability of GAF. I'd agree that exploiting threaded parallelism is highly desirable.

The configuration in this repo requires some coding in LEAN, some coding here and some config.json changes. You could simplify this with a dedicated optimization config and then modify the algorithm parameters values using reflection. It would also be possible for genetic generations to pass on parameter values through reflection. It'd be a boon to be able to optimize algorithms with zero code or config changes to LEAN. Alternatively, unobtrusive parameter Attributes might work just as well.  I like the ideas being put forward about parameters and am interested in seeing how these play out.

I think the recent changes to the desktop client would allow pushing optimization results as charting, but maybe the results pipeline would need changing to chain run result sets together? It might make sense to show running aggregations of time periods, but the results are handled as a serial queue. Apart from that, the launcher could instantiate a dedicated log file for optimizer results as it's helpful for these to be separate from trace logs.

In general, the GAF library is pretty black boxed which can make debugging tricky. Apart from that it provides a very straight-forward API, however I think it would be best to present users with a higher level of abstraction that allows configuration of param values, size of population, generations, operator probabilities etc.

**Comment by jameschch** [comment]
A few more notes: the GAF framework is more than adequate to handle generational relationships internally. It also has support for parallel executions using the TPL. I now have parallel backtests and a polished configuration model in my fork. 

It may be you could just reuse this capability rather than implement a custom threading model, at least for organic optimization. With the flexibility of custom generational operators in GAF, I quite imagine it would also be possible to perform other optimization methods using this framework.

**Comment by Worthy7** [comment]
@jaredbroad  Me and James are both actively looking to further the LeanOptimizer project and I'm just wondering if you're staying quiet due to what you said on the forums, about this being perhaps a conflict of interest in terms of QuantConnects business model. If it is then we need to know what work is and isn't worth doing. If it isn't then can we get an update please?

**Comment by jameschch** [comment]
I personally do not see a great deal of commonality between the simple genetic console app that I've been working on (predominantly for my own amusement), and the cloud-based enterprise grade machine learning solution that will be offered through QC.

I'd be happy to lend support by supplying my findings with relation to pertinent frameworks, for instance, I've thoroughly road-tested GeneticSharp and would recommend its use.

**Comment by Sdoof** [comment]
Hey folks, Just to check. I see there has been little activity is this project dead/"on ice"?

**Comment by Worthy7** [comment]
@Sdoof dead from me at least, got caught up with other things for now

**Comment by jaredbroad** [comment]
No not dead; putting the pieces together slowly. We recently upgraded the backend to support optimizer style backtesting; https://www.quantconnect.com/forum/discussion/3057/new-backtesting-cloud

Todo is code side as described in the optimizer project. As much as possible we do bugs before features though but will hopefully get to this soon. https://github.com/QuantConnect/Lean/projects/1

**Comment by Sdoof** [comment]
Thanks Folks, fantastic to see this is in the pipeline.

**Comment by crystalneth** [comment]
QuantConnect and LEAN seem really neat, and I'm considering converting over from backtrader because of the speed of QC and rich data sets available. However I've implemented a custom optimization solution on backtrader using AWS lambda and would like to be able to do similar optimizations here. I would be interested in paying for a hosted solution such as QC, however it's hard for me to imagine doing so w/o basic optimization capabilities.

I see that you've been talking about this feature for 4 years now. Can you share some information about the roadmap and direction of the product that we can count on?

**Comment by Chipply** [comment]
In a similar place here as crystalneth. Is this feature still on the road map or likely possible in the near future?

**Comment by IlshatGaripov** [comment]
Hey I think I covered this issue..
that's an optimization json that can give a little insight of functionality. https://github.com/IlshatGaripov/OptimizationLeanJames/blob/master/Optimization/optimization.json

**Comment by IlshatGaripov** [comment]
the program allows to do thousands parallel lean experiemtns in azure cloud.

**Comment by jameschch** [comment]
Anyone interested in parameter optimization for Lean is welcome to use this tool:

[https://github.com/jameschch/LeanOptimization](https://github.com/jameschch/LeanOptimization)

I have been adding features over the course of a few years and now have something fairly useful. Nothing is stopping you from scaling this out into any cloud compute provider.

You might also be interested in my .net core port, which adds some Blazor interfaces to edit config files and monitor progress of optimization:

[https://github.com/jameschch/LeanParameterOptimization](https://github.com/jameschch/LeanParameterOptimization)

Fell free to raise issues with bugs and feature ideas.

**Comment by IlshatGaripov** [comment]
@jameschch I have elaborated your code a little bit on own way. thank you very much for springboard!! I will message you with ideas little later I think that would be a great feature to all if we could get this finilized so everyone else could take advantage of it.

**Comment by omidabdi1** [comment]
Any update on IOptimizer?

**Comment by jameschch** [comment]
@IlshatGaripov Yes, my expectation is that my optimizer tools will just provide a basis for customization. I think there are now enough options to satisfy most algorithm flavors. Look forward to hearing of any improvements you think I can make. As it stands I can't think of many ways to make the starting ramp any less steep.

**Comment by IlshatGaripov** [comment]
@jameschch  I have opened an issue with some look for improvements. That would be great to discuss this further. And at some point we could probably combine our exprtise and re write all the things from a scratch - to make it easier to develop it further altogether..  Thank you!

**Comment by kayuksel** [comment]
I would definitely suggest checking the open-source Ray-Tune library, especially if multiple optimization backtests will be run in parallel: https://ray.readthedocs.io/en/latest/tune.html

Otherwise, you can simply have Hyperopt. There are also API-based hyper-parameter optimization services (such as https://sigopt.com) that you can partner with and integrate easily.
