### ISSUE TITLE
RandomDataGenerator cannot generate minute open interest data

### ISSUE THREAD

**Issue by jmerle** [QuantConnect/Lean#5871]
#### Expected Behavior

The RandomDataGenerator in the ToolBox can generate minute resolution open interest data for options and futures.

#### Actual Behavior

The RandomDataGenerator in the ToolBox can only generate daily resolution open interest data for options and futures.

#### Potential Solution

The problem seems to be the [`OpenInterestTickAggregator`](https://github.com/QuantConnect/Lean/blob/master/ToolBox/TickAggregator.cs#L148) being forced to `Resolution.Daily`, while the [`TradeTickAggregator`](https://github.com/QuantConnect/Lean/blob/master/ToolBox/TickAggregator.cs#L131) and [`QuoteTickAggregator`](https://github.com/QuantConnect/Lean/blob/master/ToolBox/TickAggregator.cs#L114) have configurable resolutions. The comments in and above [`TickAggregator.ForTickTypes()`](https://github.com/QuantConnect/Lean/blob/master/ToolBox/TickAggregator.cs#L69) suggest this behavior is intentional, but don't say why. My non-existent experience with open interest data also doesn't really help in figuring that out.

#### Reproducing the Problem

Run the ToolBox with the following arguments:
- `--destination-dir ../../../Data --app randomdatagenerator --start 20210601 --end 20210801 --symbol-count 1 --security-type Option --resolution Minute`
- `--destination-dir ../../../Data --app randomdatagenerator --start 20210601 --end 20210801 --symbol-count 1 --security-type Future --resolution Minute`

#### System Information

OS: Ubuntu 20.04

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by dtashlykov** [comment]
Echoing @jmerle comments about whether or not forcing OpenInterestTickAggregator to the daily resolution is intentional, I've ran into issues debugging futures locally _without_ Open Interest data on the minute time frame (subscribed in the minute resolution). 

After subscribing via. AddFuture, the OnData() event in a local debug _never_ triggers unless I change the Start/End dates to a date range I have _all_ minute data for -- Trade, Quote, and OpenInterest. 

With OpenInterest data missing, it appears the OnData() event never triggers, and no FuturesChain objects get passed through a Slice.
