### ISSUE TITLE
Improve SetHoldings Solution Search Algorithm

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#590]
Because brokerage fees structures are not linear, SetHoldings iterates linearly to find the right quantity.

For FX assets this can be quite slow as the quantities are high. This can be improved with a binary search on the quantity to use, or adjusting the step quantity (asset lot size from symbol properties) 

Petter solved his use case with a binary search: https://www.quantconnect.com/forum/discussion/1419/setholdings-slow-/p1

**Comment by mchandschuh** [comment]
I recall the initial implementation used an approach similar to Newton rhapson to quickly converge on a solution. It seems the current implementation decrements the order quantity on  each pass. Instead of decrementing by one on each pass, we could figure out how far off we are and determine how much quantity should change. It's OK to use linearity inside of an iterative method, it should be able to converge in under 10 iterations (barring extremely exotic fee structures).

**Comment by jaredbroad** [comment]
Resolved
