### ISSUE TITLE
lean cloud pull skips subsequent project updates

### ISSUE THREAD

**Issue by Scorillo47** [QuantConnect/Lean#5906]
#### Expected Behavior

The command "lean cloud pull" should pull the latest project updates, even if subsequent edits are done in the cloud for a linked project. 

#### Actual Behavior

The command "lean could pull" pulls the initial version of the project but then subsequent edits in the cloud seem to be ignored by subsequent "lean cloud pull" commands. 

#### Potential Solution

Somehow the linked projects appear as non-linked. This may cause "lean cloud pull" to skip the project sync? 

~~[edit] issue appears to be caused by a regression introduced by the latest version of Lean operating against local folders created by older versions~~

#### Reproducing the Problem

1. lean cloud pull
1. edit main.py in the cloud using the editor
1. lean cloud pull
1. we observe no files being synced 

#### System Information

1. Windows 10 Version 10.0.19043.1165 
2. Lean version: 1.0.65
3. Python version: Python 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Scorillo47** [comment]
I have seen one interesting behavior. If I remove the local project directory then the bug stops reproing. The next "lean cloud pull" will recreate a fresh directory, and subsequent changes in the cloud will be subsequently pulled locally correctly. 

This issue could have been related with the latest upgrade of Lean. I remember I just did a fresh Lean upgrade a few hours ago to 1.0.65. It's possible this Lean upgrade could have messed up local directory contents?

**Comment by jmerle** [comment]
Hmm, interesting. Can you please share the content of the config.json file in one of your local project directories that don't sync correctly?

Do you perhaps also remember when you first pulled the projects that don't sync correctly anymore? The last breaking change I can think of in `lean cloud pull` happened between version 0.1.7 and 0.1.8 (0.1.8 was released on 2021-02-23). If you pulled projects before that time you may experience an issue like this, although back then the CLI's readme still had bold warnings about it being a work-in-progress and that there may have been breaking changes like this one before its first beta release.

**Comment by Scorillo47** [comment]
I have created these projects about a month ago (was not even a member of QC in Februrary)

My current Lean version is 1.0.65

The bug still reproes on some of these folders. If I delete the folder and pull it again, the only thing that's changing is the cloud ID

(lean.1) C:\_git_c\inv\lean.workspace\2>type my\DumbExp6\config.json
{
    "algorithm-language": "Python",
    "parameters": {},
    "description": "",
    "cloud-id": 9274946
}

**Comment by Scorillo47** [comment]
Very strange. The bug starts happening again on the DumbExp61 which was deleted and recreated after the lean version upgrade. 

So lean version is unrelated.

**Comment by jmerle** [comment]
The issue seems to be caused by a regression in/wrongful assumption about QuantConnect's REST API. When you tell the CLI to pull a project, it will query the `/api/v2/projects/read` endpoint to get basic information about your cloud projects. Especially important is the modified timestamp of a cloud project, as we can compare that with the local modified timestamps to determine for which projects we need to query the `/api/v2/files/read` endpoint to get the latest cloud file contents. The idea behind this check is that if a project hasn't changed locally nor in the cloud, we can skip the `/api/v2/files/read` request for it which speeds up the `lean cloud pull` and `lean cloud push` commands.

What seems to be happening is that the modified timestamps in the cloud projects returned by the `/api/v2/projects/read` endpoint don't (consistently) change when one of the files in the cloud project are updated. This wrongly causes the CLI to think that there are no updates to a project's files in the cloud.

I just released a new version of the CLI that doesn't use these modified timestamps. You can update using `pip install --upgrade lean`, I hope that fixes the issue.

**Comment by Scorillo47** [comment]
One more idea. Perhaps something in the cloud side has changed the cloud IDs? So my local directories are now "orphaned" but because they have the same name as the ones in the cloud then no sync will happen. That could explain the behavior as well.



From: Adi Oltean
Sent: Sunday, September 5, 2021 4:49 AM
To: QuantConnect/Lean ***@***.***>; QuantConnect/Lean ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [QuantConnect/Lean] lean cloud pull skips subsequent project updates (#5906)

I have created these projects about a month ago (was not even a member of QC in Februrary)

My current Lean version is 1.0.65

The bug still reproes on some of these folders. If I delete the folder and pull it again, the only thing that's changing is the cloud ID

(lean.1) C:\_git_c\inv\lean.workspace\2>type my\DumbExp6\config.json
{
    "algorithm-language": "Python",
    "parameters": {},
    "description": "",
    "cloud-id": 9274946
}

**Comment by jmerle** [comment]
If the cloud id had changed the CLI would've synced to a new local directory named "<project name> 2", similar to what happens if you have two cloud projects with the same name.

Based on the email chain in your last comment I think you missed my [previous comment](https://github.com/QuantConnect/Lean/issues/5906#issuecomment-913149495) which should solve the issue.

**Comment by Scorillo47** [comment]
looks like the Git comments got interleaved with wrong timestamps (replying via email is not the same as replying in thread) 

Anyway, I have upgraded the lean cli and the issue seems gone. Will close the issue for now.

Thanks! 
Adi
