### ISSUE TITLE
docker build failed

### ISSUE THREAD

**Issue by boskiv** [QuantConnect/Lean#6206]
Trying to build dockerfile but got
```
COPY ./DataLibraries /Lean/Launcher/bin/Debug/
COPY ./AlphaStreams/QuantConnect.AlphaStream/bin/Debug/ /Lean/Launcher/bin/Debug/
COPY ./Lean/Launcher/bin/Debug/ /Lean/Launcher/bin/Debug/
COPY ./Lean/Optimizer.Launcher/bin/Debug/ /Lean/Optimizer.Launcher/bin/Debug/
COPY ./Lean/Report/bin/Debug/ /Lean/Report/bin/Debug/
```
Did `dotnet build -f net5.0 /p:Configuration=Release /v:quiet /p:WarningLevel=1 QuantConnect.Lean.sln` before without errors
```
 42 Warning(s)
    0 Error(s)
```

OSX Monteray 12.2.1. Docker for mac 4.4.2 (73305)

**Comment by Martin-Molinero** [comment]
Hey @boskiv!
Some of those dependencies are other repositories that also require being built to get the full Lean image. You can remove them if not required for you. Some of the data sources at https://github.com/QuantConnect?q=Lean.DataSource&type=all&language=&sort= & https://github.com/QuantConnect/AlphaStreams .

Instead of building Lean from scratch what you could do is a custom dockerfile which uses lean as the base `from quantconnect/lean` and perform any custom operation you need.

Hope it helps!
