### ISSUE TITLE
I suggest renaming default `master` branch to `main`

### ISSUE THREAD

**Issue by v-karbovnichy** [QuantConnect/Lean#6223]
The world is changing, and this is one of the global changes happening.

Go to repo Settings > Branches, and click on pencil (Rename) button to rename `master` branch to `main`.

![image](https://user-images.githubusercontent.com/7301634/154678162-484ecc42-3795-4ddc-95cc-b806afe21409.png)

**Comment by femtotrader** [comment]
Here are some pros and cons of such renaming... (thanks to Claude.ai)

Naming a Git principal branch "main" instead of "master" is recommended for several reasons:

1. Inclusive language:
The term "master" has historical connections to slavery, where it referred to a person who had ownership over others. In the context of software development, this can be seen as insensitive and exclusionary. By contrast, "main" is a neutral term that doesn't carry these problematic connotations. This change promotes a more inclusive environment in the tech community, making it more welcoming to people from diverse backgrounds.
2. Accuracy:
In Git, the default branch isn't really a "master" in the sense of controlling other branches. It's simply the primary or default branch where the main development occurs. "main" more accurately describes its role in the repository as the principal line of development. This naming aligns better with the branch's actual function and purpose in the Git workflow.
3. Industry trend:
Major platforms like GitHub, GitLab, and Bitbucket have adopted "main" as the default branch name for new repositories. Many large tech companies and open-source projects have also made this switch. This shift creates a new standard in the industry, and following it helps maintain consistency across different platforms and projects.
4. Consistency with programming concepts:
In many programming languages, the entry point of a program is often called the "main" function. Using "main" as the name for the principal branch creates a nice parallel with this concept, reinforcing the idea that this branch is the starting point or core of the project.
5. Ease of transition:
Git itself and major hosting platforms have implemented features to make the transition from "master" to "main" easier. Git provides commands to rename branches and set a different default branch name for new repositories. Platforms like GitHub offer automated tools to rename the default branch and update references, making the process smoother for existing projects.

See https://github.com/github/renaming

on the other side

While changing from "master" to "main" is generally seen as positive, there are some potential challenges:

1. Legacy system compatibility:
Some older tools, scripts, or CI/CD pipelines may have "master" hardcoded, requiring updates.
2. Team adaptation:
Team members need to adjust their habits and muscle memory, which can temporarily slow down workflows.
3. Documentation updates:
Existing documentation, guides, and tutorials referencing "master" will need revision.
4. External dependencies:
Projects depending on or referencing your repository may need to update their configurations.
5. Inconsistency during transition:
During industry-wide transition, developers may encounter both naming conventions, potentially causing confusion.
6. Potential for errors:
Renaming could lead to mistakes if not done carefully, such as broken references or lost commits.
7. Resistance to change:
Some developers may oppose the change, viewing it as unnecessary or politically motivated.
8. SEO and discoverability:
Existing links or search results pointing to "master" may need updating.
