### ISSUE TITLE
Fill forward resolution nondeterministic addition case 

### ISSUE THREAD

**Issue by rjra2611** [QuantConnect/Lean#6255]
#### Expected Behavior

- `AlgorithmManager.DataPoints` should be the same each time the algorithm is run

#### Actual Behavior

- https://github.com/QuantConnect/Lean/pull/6245 helped uncover a non deterministic behavior
- `AlgorithmManager.DataPoints` is not the same every time. It comes out to be different in every non periodic number of runs.
#### Potential Solution

- Not available 
#### Reproducing the Problem

See `OptionChainSubscriptionRemovalRegressionAlgorithm`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
`OptionChainSubscriptionRemovalRegressionAlgorithm` as well as `MultiUniverseSharedSecurityRegressionAlgorithm` added by `https://github.com/QuantConnect/Lean/pull/6959/files` suffer of a similar issue like https://github.com/QuantConnect/Lean/issues/6253 but while adding subscriptions instead of removing.
In this case, Lean adds **first** the universe subscriptions with lower frequency resolution (Hour for `MultiUniverseSharedSecurityRegressionAlgorithm` & Minute for `OptionChainSubscriptionRemovalRegressionAlgorithm`) and **later** the `AddSecurity` calls with higher frequency resolution. But there's a race condition because the data feed workers start to generate the data right away and while doing so the fill forward resolution gets adjusted to a higher frequency due to the `AddSecurity` call
