### ISSUE TITLE
Installation failed on Linux

### ISSUE THREAD

**Issue by xros** [QuantConnect/Lean#654]
OS: ubuntu 14.04 amd64
I was following the tutorial but it failed at here when using `mono nuget.exe` to restore settings.

`mono nuget.exe restore QuantConnect.Lean.sln`

And the error log is here: http://paste.ubuntu.com/23624302/
```
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
WARNING: Error getting response stream (Write: The authentication or decryption has failed.): SendFailure
WARNING: The initialization function tries to access Value on this instance
WARNING: The initialization function tries to access Value on this instance
Unable to find version '2.2.0-xbuild02' of package 'Baseclass.Contrib.Nuget.Output'.
Unable to find version '2.7.5' of package 'IronPython'.
Unable to find version '2.1.3' of package 'fasterflect'.
Unable to find version '3.1.2.1' of package 'FSharp.Core'.
Unable to find version '3.7.0' of package 'MathNet.Numerics'.
Unable to find version '7.0.1' of package 'Newtonsoft.Json'.
Unable to find version '1.3.1' of package 'NodaTime'.
Unable to find version '105.2.3' of package 'RestSharp'.
Unable to find version '1.2' of package 'CloneExtensions'.
Unable to find version '1.9.3' of package 'DotNetZip'.
Unable to find version '0.86.0' of package 'SharpZipLib'.
Unable to find version '0.1.1-alpha' of package 'MathNet.Filtering'.
Unable to find version '0.1.20.0' of package 'AsyncIO'.
Unable to find version '3.3.3' of package 'Castle.Core'.
Unable to find version '7.3.4830.1' of package 'IKVM-WithExes'.
Unable to find version '4.5.10' of package 'Moq'.
Unable to find version '3.3.3.4' of package 'NetMQ'.
Unable to find version '2.6.4' of package 'NUnit'.
Unable to find version '1.0.4.0' of package 'WebSocketSharpFork'.
Unable to find version '6.2.2' of package 'ImpromptuInterface'.
Unable to find version '0.85.4.369' of package 'ICSharpCode.SharpZipLib.dll'.
Unable to find version '1.0.5' of package 'GeckoFX'.
Unable to find version '4.5.21' of package 'Moq'.
Unable to find version '3.4.1' of package 'NUnit'.
Unable to find version '3.0.2' of package 'Accord'.
Unable to find version '3.0.2' of package 'Accord.Fuzzy'.
Unable to find version '2.7.5' of package 'IronPython.StdLib'.
Unable to find version '0.64' of package 'SevenZipSharp'.
```

Do you know how to fix it?  (if nuget has lost all those defined versioned packages)

**Comment by jameschch** [comment]
Just a guess, but did you try 

sudo apt-get update

...after adding the mono sources?

**Comment by andrewhart098** [comment]
I was able to get Lean running on a fresh install of ubuntu 16.04.  Could you please confirm the version of nuget you are using? The version I used was: 2.12.0.0.

One thing you may try is installing nuget via apt-get.  So `apt-get install nuget`

Then, when restoring the packages, the command is:

`nuget restore QuantConnect.Lean.sln`

**Comment by rbrok** [comment]
@xros 
I had the same problem and it is a certificate conflict.
Did you follow the certificate statement? 
I wasn't able to fix that problem with debian jessy and the mono repo.

I have upgraded my system to debian testing and it was possibly to execute nuget without problems.
As andrewhart098 has noted. There is a nuget available via mono package. The certificate problem occurs wirh both nuget versions..

It is not easy to get quantconnect to run on linux, but it's worth it. (I'm a beginner...)

**Comment by jaredbroad** [comment]
Thanks for the feedback @rbrok. Closing issue as nuget/certificate bug not LEAN bug.

**Comment by xros** [comment]
@rbrok I found we had the same issue. And after downloading the latest nuget from nuget.org , it works.  CA issue not the software i guess

**Comment by taylerallen6** [comment]
> I was able to get Lean running on a fresh install of ubuntu 16.04. Could you please confirm the version of nuget you are using? The version I used was: 2.12.0.0.
> 
> One thing you may try is installing nuget via apt-get. So `apt-get install nuget`
> 
> Then, when restoring the packages, the command is:
> 
> `nuget restore QuantConnect.Lean.sln`

@andrewhart098 How did you install nuget 2.12? I am using ubuntu 16.04 and apt-get install nuget only installs version 2.8.7.0. Because of this, I can't build at all.

**Comment by jaredbroad** [comment]
@taylerallen6 - 
```
wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
mono nuget.exe restore QuantConnect.Lean.sln
```

**Comment by taylerallen6** [comment]
Thanks for the quick response! Unfortunately that didnt work.

`>>>$ wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
--2018-12-20 18:20:24--  https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
Resolving dist.nuget.org (dist.nuget.org)... 152.199.4.33
Connecting to dist.nuget.org (dist.nuget.org)|152.199.4.33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5687056 (5.4M) [application/x-msdownload]
Saving to: ‘nuget.exe.1’

nuget.exe.1                100%[=======================================>]   5.42M  7.20MB/s    in 0.8s    

2018-12-20 18:20:25 (7.20 MB/s) - ‘nuget.exe.1’ saved [5687056/5687056]

>>>$ mono nuget.exe restore QuantConnect.Lean.slnMSBuild auto-detection: using msbuild version '15.0' from '/usr/lib/mono/msbuild/15.0/bin'.
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.BadImageFormatException: Could not resolve field token 0x0400033d, due to: Could not load type of field 'Microsoft.Build.Execution.BuildManager:_workQueue' (32) due to: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:/usr/lib/mono/msbuild/15.0/bin/Microsoft.Build.dll type:BuildManager member:(null)
File name: 'Microsoft.Build'
  at Microsoft.Build.CommandLine.MSBuildApp.BuildProject (System.String projectFile, System.String[] targets, System.String toolsVersion, System.Collections.Generic.Dictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.Dictionary`2[TKey,TValue] restoreProperties, Microsoft.Build.Framework.ILogger[] loggers, Microsoft.Build.Framework.LoggerVerbosity verbosity, Microsoft.Build.CommandLine.DistributedLoggerRecord[] distributedLoggerRecords, System.Int32 cpuCount, System.Boolean enableNodeReuse, System.IO.TextWriter preprocessWriter, System.Boolean detailedSummary, System.Collections.Generic.ISet`1[T] warningsAsErrors, System.Collections.Generic.ISet`1[T] warningsAsMessages, System.Boolean enableRestore, Microsoft.Build.Logging.ProfilerLogger profilerLogger, System.Boolean enableProfiler) [0x004e3] in <e16d15a2cbfd4badb14a71a629ebef7f>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x00184] in <e16d15a2cbfd4badb14a71a629ebef7f>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.BadImageFormatException: Could not resolve field token 0x0400033d, due to: Could not load type of field 'Microsoft.Build.Execution.BuildManager:_workQueue' (32) due to: Could not load file or assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. assembly:/usr/lib/mono/msbuild/15.0/bin/Microsoft.Build.dll type:BuildManager member:(null)
File name: 'Microsoft.Build'
  at Microsoft.Build.CommandLine.MSBuildApp.BuildProject (System.String projectFile, System.String[] targets, System.String toolsVersion, System.Collections.Generic.Dictionary`2[TKey,TValue] globalProperties, System.Collections.Generic.Dictionary`2[TKey,TValue] restoreProperties, Microsoft.Build.Framework.ILogger[] loggers, Microsoft.Build.Framework.LoggerVerbosity verbosity, Microsoft.Build.CommandLine.DistributedLoggerRecord[] distributedLoggerRecords, System.Int32 cpuCount, System.Boolean enableNodeReuse, System.IO.TextWriter preprocessWriter, System.Boolean detailedSummary, System.Collections.Generic.ISet`1[T] warningsAsErrors, System.Collections.Generic.ISet`1[T] warningsAsMessages, System.Boolean enableRestore, Microsoft.Build.Logging.ProfilerLogger profilerLogger, System.Boolean enableProfiler) [0x004e3] in <e16d15a2cbfd4badb14a71a629ebef7f>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Execute (System.String commandLine) [0x003f2] in <e16d15a2cbfd4badb14a71a629ebef7f>:0 
  at Microsoft.Build.CommandLine.MSBuildApp.Main () [0x00028] in <e16d15a2cbfd4badb14a71a629ebef7f>:0 

WARNING: Error reading msbuild project information, ensure that your input solution or project file is valid. NETCore and UAP projects will be skipped, only packages.config files will be restored.
All packages listed in packages.config are already installed.
`

**Comment by taylerallen6** [comment]
Im going to submit a new issue. There is more issues and this is something that should have its own issue.
