### ISSUE TITLE
no module named pandas

### ISSUE THREAD

**Issue by mit10000** [QuantConnect/Lean#6574]
#### Expected Behavior
on Windows can run official example

#### Actual Behavior
encountered error
I followed instructions here https://github.com/QuantConnect/Lean/tree/master/Algorithm.Python#quantconnect-python-algorithm-project
1
 install anaconda
2
add python.exe to PATH
3
Create PYTHONNET_PYDLL environment variable
value=C:\Users\desheng\AppData\Local\Continuum\anaconda3\python36.dll
4
In anaconda "base" env
(base)C: pip install pandas==0.25.3
5
confirm pandas installed
(base) C:\python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
 import pandas
 exit()
6
in VS 2022 , modify config.json
"algorithm-language": "Python",//"CSharp",
"algorithm-location": "../../../Algorithm.Python/BasicTemplateFrameworkAlgorithm.py"
7
built, F5
pandasConverter.cs line41
                    _pandas = Py.Import("pandas");
report Error:
Python.Runtime.PythonException: 'No module named 'pandas''

Please help, thanks!

#### System Information
Windows 10
Visual Studio 2022
Anaconda 4.6.7
pandas 0.25.3

**Comment by Martin-Molinero** [comment]
Hey @mit10000!
Sorry for the inconvenience but we do not give support for custom installs due to the infinite combination of OS, packages and setups. We strongly suggest users use the lean [CLI ](https://www.lean.io/cli/)instead.
> PYTHONNET_PYDLL 

Just a guess, did you restart vscode after setting the env, It might be required for it to be picked up I believe
