### ISSUE TITLE
`IndicatorExtensions` cannot be used with `PythonIndicator`

### ISSUE THREAD

**Issue by LouisSzeto** [QuantConnect/Lean#6615]
#### Expected Behavior
`IndicatorExtensions` can be used with `PythonIndicator` for all method (`Of`, `Over`,...)

#### Actual Behavior
For `Of`:
It will throw error of `Cannot perform runtime binding on a null reference in PythonIndicator.cs:line 143`
It looks like it didn't read the PythonIndicator's value correctly.

For others:
The combination method didn't get called at all, just like https://github.com/QuantConnect/Lean/issues/3565#issuecomment-1113254800

#### Potential Solution
NA

#### Reproducing the Problem
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_8bbd321995671f7f48427d27a4bd29d6.html

#### System Information
QC cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
I am reopening this issue because `IndicatorExtensions.sma` ([fc02262](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_fc02262fbf26e3da2b90cf549e553f6a.html)) is not working and https://github.com/QuantConnect/Lean/issues/6615 didn't test it.

**Comment by Marinovsky** [comment]
After debugging the regression test attached to this issue, I found the second indicator wasn't being updated since the first indicator was being updated manually. When calling `self.range_indicator.update(data.bars.get(self.qqq))`, instead of calling the base implementation of the indicator `BaseIndicator<T>.Update()`  it called directly the python definition of the `update` method. Therefore, the method `OnUpdated` was never called, so the action attached to `Updated` was also never called, and thus the second indicator was not updated. Still, you can fix the algo by doing this:

Instead of defining an `update` method in the custom python class, you can define a method called `compute_next_value` which overrides the base method `ComputeNextValue`. That way, when you call `self.range_indicator.update(data.bars.get(self.qqq))`, LEAN will call the base implementation `BaseIndicator<T>.Update()` that will call on its time the attached action in `Updated`.
![image](https://github.com/user-attachments/assets/a81a9785-2b5a-457d-af62-12225605e3b5)

**Comment by DerekMelchin** [comment]
`is_ready` doesn't seem to work with custom python indicators

```
from collections import deque

class CustomSimpleMovingAverage(PythonIndicator):
    def __init__(self, name, period):
        self.name = name
        self.warm_up_period = period
        self.time = datetime.min
        self.value = 0
        self.queue = deque(maxlen=period)

    def update(self, input: BaseData) -> bool:
        self.queue.appendleft(input.value)
        count = len(self.queue)
        self.time = input.time
        self.value = sum(self.queue) / count
        print(count == self.queue.maxlen)
        return count == self.queue.maxlen

sma = CustomSimpleMovingAverage('sma', 3)
qb = QuantBook()
spy = qb.add_equity('SPY').symbol
for bar in qb.history[TradeBar](spy, 5, Resolution.DAILY):
    sma.update(bar)
print(f'Done: {sma.is_ready}')
```

> False
> False
> True
> True
> True
> Done: False
