### ISSUE TITLE
RPCs to support integrations with any language

### ISSUE THREAD

**Issue by seanlaff** [QuantConnect/Lean#6738]
The LEAN engine has some great abstractions/interfaces (`IDataFeed`, `ITransactionHandler`, etc) that are pluggable. However, it's difficult to implement these interfaces in languages other than C#/python. 

Has there been any consideration to exposing these services over some sort of rpc/socket/protocol? 

I would like to run the LEAN container and interact with it as a service via other toolchains (go, zig, js, etc).

**Comment by mw66** [comment]
@seanlaff Guess there won't be official support for RPC soon, but you can always do it yourself making Lean either as rpc server / or client, and contribute back :-)

**Comment by jaredbroad** [comment]
We had prototypes of this and the backtesting process was just too slow. Since it's all event-driven the synchronous RPC overhead was enough to slow it all by 10x. We also could not afford the bandwidth to maintain N copies of documentation with all the different examples of variations on the API so had to narrow the focus to the two most popular.
