### ISSUE TITLE
Net Profit Discrepancy with Dividend Payments

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#6815]
#### Expected Behavior

If we have two algorithms where one uses raw prices and the other uses adjusted prices, and we make the same trades in both algorithms, the ending net profit should be the same between both algorithms.

#### Actual Behavior

The ending net profit and equity can be different.

#### Potential Solution

N/A

#### Reproducing the Problem

- [Backtest with raw prices](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_26456cecfdefc6395eaf6c84c70c6ded.html)
- [Backtest with adjusted prices](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_5c9f4332ceeb0a22c3e2c7daf4c64fc5.html)

#### System Information

QC Cloud

#### Checklist

- [ ] I have completely filled out this template
- [ ] I have confirmed that this issue exists on the current `master` branch
- [ ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by DerekMelchin** [comment]
[This CSV](https://github.com/QuantConnect/Lean/files/10289497/Factor.File.Testing.-.Price.Simulations.csv) shows an example. We run two algorithms: one with raw data and one with adjusted data. Each algorithm places one round-trip trade. We give the same amount of capital to the trade in both algorithms, yet they have different ending equity values because of the dividend payment.

**Comment by jaredbroad** [comment]
We performed a few weeks research here; including pulling information from blogs and multiple data vendors on their techniques for adjusting pricing. The short story is:
 - Adjusted pricing systems are all imperfect approximations due to the precise overnight gap on the dividend date being unknown. 
 - The only way to make them perfect would introduce look ahead bias; i.e. adjusting the factor by the precise overnight gap of the single stock ahead of time would make a slightly more accurate factor in some circumstances by would introduce knowledge of the gap into the factors.
 - The most accurate is to use raw prices.
 - A nice feature would be to get the price factors back to the algorithm so users can create the adjusted and raw prices in the same space, i.e. create indicators with the adjusted pricing but model the portfolio with the raw pricing.
