### ISSUE TITLE
I cannot update my fork for a pull request

### ISSUE THREAD

**Issue by bizcad** [QuantConnect/Lean#69]
I was able to fork Lean into my Github account.  I then cloned it into VS2013 Pro and cleaned up the XML missing comments.  I commited the changes to my local repo.  When I tried to push or sync the changes, I get...
An error occurred. Detailed message: Response status code does not indicate success: 403 (Forbidden).

When I look at pull requests, I can do a new PR and compare files, but they are the same between my fork on GitHub and the QuantConnect/Lean on GitHub.  

What do I need to do?

Sorry about the newbie question.  I just wanted to make sure I could do a pull and commit before I started really adding my indicators.  Good thing I did too.

Nick

**Comment by mchandschuh** [comment]
This is typically caused by cloning the QuantConnect/Lean directly and then trying to push. You'll need to clone you're fork of the repo (https://github.com/bizcad/Lean.git) and then you'll be able to push into there. After you push into your github repo you'll be able to submit a pull request with your changes. Here's some documentation by github on the fork and pull model: https://help.github.com/articles/using-pull-requests/.  Please let us know if you have any further issues.
