### ISSUE TITLE
SetHoldings for Multiple Targets and Liquidating Existing Holdings Close Some Positions

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#7008]
#### Expected Behavior
`SetHoldings` for multiple targets should open one position for each target.

#### Actual Behavior
If the `SetHoldings` has two targets, it creates 3 orders: the first order opens a position for A, the second order closes the position for A, and the third order opens a position for B. This is because `SetHoldings` for one target closes all positions before it opens its positions.

#### Potential Solution
Liquidate existing all positions before starting to open new ones. 

#### Reproducing the Problem
```csharp
public override void OnData(Slice data)
{
    if (!Portfolio.Invested)
    {
        SetHoldings(new List<PortfolioTarget> { new("SPY", 0.8m), new("IBM", 0.2m) },
            liquidateExistingHoldings: true);
        }
}
```

Creates 3 orders instead of two. SPY has zero shares after the call.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by yul** [comment]
> Potential Solution
> Liquidate existing all positions before starting to open new ones.

I don't think this is a good solution. I expect liquidateExistingHoldings parameter to be aware of portfolio changes. If I just wanted to liquidate all holdings, I could add self.Liquidate() before the self.SetHoldings() call.
With this fix it will liquidate SPY completely and then buy it again, which will cause significant and unnecessary losses.
I expect from this parameter to
a) liquidate holdings that are not mentioned in Portfolio Targets;
b) rebalance holdings that are mentioned in Portfolio Targets and have positions in Portfolio;
c) open new positions for Portfolio Targets that do not have positions open yet.
Otherwise I really don't see a point in having this parameter.

**Comment by yul** [comment]
Actually, from backtesting it looks like this is how it actually works, so nevermind.
