### ISSUE TITLE
security.Price isn't the latest close price

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7319]
#### Expected Behavior

`security.Price` is the latest close price of the security

#### Actual Behavior

In the attached backtest, `security.Price` is not the latest close price of the security.

#### Potential Solution

N/A

#### Reproducing the Problem

[This backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_427de27541591b3ace618a8dd3849d06.html) prints  
> Quit(): Price: 4773.0; Close: 4772.75; fillForward: False

#### System Information

QC Cloud

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This is the expected behavior because for options/futures we use quotes to drive the price because they can be illiquid and the last trade can be way off, compared to the current bid/ask. If desired trade information can be accessed specifically using `security.Cache.GetData<TradeBar>()/security.Cache.GetData[TradeBar]()`
