### ISSUE TITLE
AlgorithmPerformance instantiates PortfolioStatistics with the default tradingDaysPerYear = 252 regardless of securities

### ISSUE THREAD

**Issue by jsboige** [QuantConnect/Lean#7562]
#### Expected Behavior

I would assume that tradingDaysPerYear accounts for the Brokerage model being used.

#### Actual Behavior

It seems that AlgorithmPerformance doesn't do that and assumes the default tradingDaysPerYear = 252 regardless of securities. Unless I'm missing a compensating effect, this has serious consequences for instance for crypto as it would ruin annual performance and Sharpe ratio.

#### Potential Solution

I haven't looked in detail, but I guess tapping into the securities market hours shouldn't be too hard.

#### Reproducing the Problem

Well launching a crypto backtest and placing a breakpoint at https://github.com/QuantConnect/Lean/blob/master/Common/Statistics/PortfolioStatistics.cs#L249 to figure out how Sharpe ratio was computed made me find out about it. 

#### System Information

Windows Server 2019

#### Checklist

- [X ] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
- Add a new `IAlgorithmSettings` property `int? TradingDaysPerYear`
- Add same property to `AlgorithmConfiguration` set by from `algorithm.Settings`, this is so that the report generator can access it too -> report generator should start using this value (if != 0 for backwards compatibility case, handling previous version results)
- After algorithm initialization, based on the brokerage model we can default to 252 or 365 as `TradingDaysPerYear` value, if it hasn't been set by the algorithm
