### ISSUE TITLE
Daily History Request Returns an Extra Day for Delisted Asset

### ISSUE THREAD

**Issue by DerekMelchin** [QuantConnect/Lean#7740]
#### Expected Behavior

If an asset is delisted on 2019-02-02, then a history request should not include a 2019-02-02 bar.

#### Actual Behavior

```
qb = QuantBook()
qb.History(qb.Symbol('IEI R735QTJ8XC9X'), datetime(2019, 1, 25), datetime(2019, 2, 5), Resolution.Daily)
```
![image](https://github.com/QuantConnect/Lean/assets/38889814/b21c4088-e65a-464b-83e2-655c5e9a015c)

#### Potential Solution

N/A

#### Reproducing the Problem

[This backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_7aeaeb1b9ce0a6a9cbbc7bf8297ffcf2.html) shows the delisting events
Logs:

> 2019-02-01 00:00:00 : | 2019-02-01 00:00:00 // 0
2019-02-02 00:00:00 : | The security with symbol 'IEI' is marked as non-tradable.
2019-02-02 00:00:00 : | 2019-02-02 00:00:00 // 1

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jhonabreul** [comment]
The last row is not an extra day, but the data for Feb01. Data in dataframes is indexed by `EndDate`, if you try the same case in C# you will see the last bar has `Time=Feb01;EndTime=Feb02` (see [this backtest](https://www.quantconnect.com/terminal/clone/-/58a14409d9f6ddb2ca37f8149b2eeccf/clone-of%3A-sleepy-fluorescent-pink-anguilline)).

<img width="652" alt="image" src="https://github.com/QuantConnect/Lean/assets/25215064/dc47f97b-cb46-4c6a-8694-840c4e702ffa">

In this specific case the volume is 0 because the data is being fill forwarded and the last raw data is for Jan31.

This might be more of a data issue or just about how Lean models daily data, with the `Time` being the actual day the data is for. 

Check [this other backtest](https://www.quantconnect.com/terminal/clone/-/9d83e5153ff243ef6a6092eb4041638f/clone-of%3A-formal-fluorescent-pink-bear) for a different asset, for which the last data is actually on the day before the delisting date.

<img width="874" alt="image" src="https://github.com/QuantConnect/Lean/assets/25215064/fc6a9ba0-cd80-4113-ba83-6fc38e77ee2d">

**Comment by jhonabreul** [comment]
In fact. this is a data issue, because the last trading date for the asset in the example was Jan 31 2019, being the delisting date actually Feb 01, not Feb 02 (which was a Saturday, btw).

References for the delisting (a merger with CenterPoint Energy, Inc.):

- https://www.centerpointenergy.com/en-us/corporate/about-us/news/1201
- https://investors.centerpointenergy.com/corporate-transactions#:~:text=On%20February%201%2C%202019%20CenterPoint%20Energy%2C%20Inc.%20(CNP)%20completed%20its%20acquisition%20(Merger)%20of%20Vectren%20Corporation 
- https://www.macrotrends.net/stocks/delisted/VVC/Vectren%20Corporation/stock-price-history#:~:text=The%20latest%20closing%20stock%20price%20for%20Vectren%20Corporation%20on%20January%2031%2C%202019%20is%2072.38

**Comment by Martin-Molinero** [comment]
Data issue created https://www.quantconnect.com/forum/discussion/16639/iei-r735qtj8xc9x-daily-the-issue-starts-from-feb-1st-2019-12-00-am-and-continues-until-feb-2nd-2019-11-59-pm/p1
