### ISSUE TITLE
Expand Duplicate Option Exercise Error Message to Diagnose Issue

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#7815]
#### Expected Behavior
Error message for duplicate option exercise would include information to reproduce the very rare bug, like a stack trace or information about the data / price / values that led to the issue.

#### Actual Behavior
At the moment, it just says to contact support but since the bug can't be reproduced easily it's impossible to make progress on. 
Runtime Error: Duplicate option exercise order request for symbol XLK 121020P00036000. Please contact support in BacktestingBrokerage.cs:line 481. 

#### Potential Solution
Capture as much information as possible and log it all. 

#### System Information
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by danaldea** [comment]
Here's another example for this error:

https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_46a511bcd9cf08854bd9ad328ead1cec.html

The code contains a list of contracts that I'm manually avoiding because they had errors in the backtest.

This way I can still do a full length backtest but takes a long time to go through all the exeptions.

What I've seen is that this error occurs only when I'm generating a take profit order for a cash secure put.

In my code I'm cancelling the TP order on assignment but in these rare cases my feeling is that there are 2 things happening:
1. assignment happens
2. the TP is converted somehow to a buy stock order --> another assignment

Hope this helps, this issue has been bugging me a lot, really slows down backtesting as I need to run a backtest until I get an error and then add the contract to the exceptions list.
