### ISSUE TITLE
Support Dynamic Margin Requirements [Oanda]

### ISSUE THREAD

**Issue by benjaminthedonkey** [QuantConnect/Lean#783]
I'm having issues with free margin calls, this only happens if there are already open positions when the algo starts.. looks like a sync issue to me. Is this implemented ? I mean , the sync of already open positions in the account?. I'm using setHoldings function to open new tardes.

At the same time, each forex symbol in OANDA has it own [margin requirements](https://www.oanda.com/resources/legal/united-states/legal/margin-rates). I wonder if it would make sense to add this to symbol-properties-database.csv and use it to set the leverage instead of the default 50:1.

Thanks.

**Comment by benjaminthedonkey** [comment]
Hi

I'v made an  attempt to  implement the  minimum margin requirement  [here]( https://github.com/QuantConnect/Lean/compare/master...benjaminthedonkey:master ) . The initial value comes from  symbol-properties-database.csv and it can be overwritten using the SetLeverage() function.   I created a new  MarginModel to handle the change but I'm not sure if it's a better idea to just modify the  SecurityMarginModel class.  I also added a few test cases.. Please share your thoughts.

**Comment by jaredbroad** [comment]
Thank you @benjaminthedonkey - its pretty good! I've given it a quick review and my only concern might be that the GetDefault currently defaults to 50x leverage. Anywhere we create securities this has to be carefully reviewed to make sure it won't impact statistics.

It also might make sense to put the MinimumMarginRequirement updates on the SecurityMarginModel rather than making another class which replicates lots of the previous code.

Long term we planned on making the margin loaded from a file/data-source - as for most providers the margin requirement changes over time based on environmental risk. Given this it would be worth thinking - how can we engineer this in a way where we could migrate this code in steps? Start with a fixed number like this and moving to a variable we set as it changes?

Given it needs to change; perhaps not putting it in the symbol properties database but re-using the SetLeverage method is the best call - so securities can be updated with meta-data as time passes.

I'm brain storming so welcome feedback from you & community. Where should we store margin requirements files, how should they be formatted, and how can we select the defaults (your work does the defaults nicely).

**Comment by benjaminthedonkey** [comment]
Happy to help @jaredbroad .  I agree on putting MinimumMarginRequirement  on the SecurityMarginModel and not creating a new class with lots of duplicate code. 

Regarding GetDefault method, from what I saw it's only used when the symbol is missing from the database. I'd argue the necessity of such a mechanism, I personally would prefer to get an error than to assume potentiality incorrect values in that case.

**Comment by StefanoRaggi** [comment]
This is a feature that could possibly be implemented in the future with Oanda/Forex historical margin data files.
We have something similar done for Futures in `FutureMarginModel` using CSV margin files:
https://github.com/QuantConnect/Lean/tree/master/Data/future/usa/margins

**Comment by ebengtso** [comment]
The margin requirements from oanda can be taken from their API when in live mode.

Check their documentation: http://developer.oanda.com/rest-live-v20/account-ep/

about their API: https://api-fxtrade.oanda.com/v3/accounts/<ACCOUNT>/instruments

Here is an example. You can take the margin from the marginRate field
`{
  "instruments": [
    {
      "displayName": "USD/THB", 
      "displayPrecision": 3, 
      "marginRate": "0.05", 
      "maximumOrderUnits": "100000000", 
      "maximumPositionSize": "0", 
      "maximumTrailingStopDistance": "100.000", 
      "minimumTradeSize": "1", 
      "minimumTrailingStopDistance": "0.050", 
      "name": "USD_THB", 
      "pipLocation": -2, 
      "tradeUnitsPrecision": 0, 
      "type": "CURRENCY"
    }, 
    {
      "displayName": "GBP/CHF", 
      "displayPrecision": 5, 
      "marginRate": "0.05", 
      "maximumOrderUnits": "100000000", 
      "maximumPositionSize": "0", 
      "maximumTrailingStopDistance": "1.00000", 
      "minimumTradeSize": "1", 
      "minimumTrailingStopDistance": "0.00050", 
      "name": "GBP_CHF", 
      "pipLocation": -4, 
      "tradeUnitsPrecision": 0, 
      "type": "CURRENCY"
    }, ...`

**Comment by jaredbroad** [comment]
Closing just because it impacts so few; and only when people are maxing out their total available leverage to the point of getting margin calls; and only on one brokerage.
