### ISSUE TITLE
Review Accounting After a Cash Sync

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8010]
#### Expected Behavior
After a cash sync, the cashbook shouldn't change a lot.

#### Actual Behavior
The live deployment to Kraken starts with:

```
CashBook Total Value:                ₿0.24
2024-04-05T00:00:49.7808038Z TRACE:: Total margin information: TotalMarginUsed: 0.18, MarginRemaining: 0.06
```

Then we have a cash sync where the margin information jumps:

```
2024-04-05T11:45:00.0572082Z TRACE:: Brokerage.PerformCashSync(): Sync cash balance
2024-04-05T11:45:10.4329261Z TRACE:: Total margin information: TotalMarginUsed: 0.13, MarginRemaining: 0.32
```

#### Potential Solution
N/A

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
5 is pretty big in BTC which is what the user is using, so it should be relative to the TPV I think

![image](https://github.com/QuantConnect/Lean/assets/18473240/91e2754a-02da-449d-95d5-4ac15b9166d1)


kraken, sounds like it accounting for the holdings again on each cash sync but should be the first only really

![image](https://github.com/QuantConnect/Lean/assets/18473240/4accfd4e-e3ff-4793-8b29-90380f17efa3)

**Comment by Marinovsky** [comment]
After doing some research about this bug I found the following things:

1. I found that the Margin Remaining value changes even without applying the balances values obtained from Kraken API each time the method `KrakenBrokerage.GetCashBalance()` is called. To find that I ran the algo `BasicTemplateCryptoAlgorithm` using live-kraken environment and USD as account currency, and commented the following line (531) so that the new balance cash amount wasn't applied to the algorithm's Cashbook:
![image](https://github.com/QuantConnect/Lean/assets/47573394/e1ab26a4-a546-4970-809d-f4e68375c7e2)
![image](https://github.com/QuantConnect/Lean/assets/47573394/9c678209-63da-4aac-803e-74a1f23f72cd)
![image](https://github.com/QuantConnect/Lean/assets/47573394/1ac0d543-4904-42e4-aa51-3d8c7e2ddd33)

2. Martin and I thought that the MarginReamining value could have been changing since Kraken was taking into account the profit/loss of an open position so that `KrakenBrokerage.GetCashBalance()` was always adjusting to the current price, profit/loss included, but LEAN wasn't. In order to see if our hypothesis was right we took 2 snapshots (with a difference of 10 minutes between them) of the state of the LEAN Holdings, Cashbook and TPV as well as the Holdings and Cash balances from Kraken API responses. After comparing those snapshots we found that the responses from the Kraken API changed just in two fields (`value` and `net`) but those weren't used when computing the cash balances for LEAN. Below is a screenshot of the difference between the Kraken resposes as well as the file with the two snapshots:
![image](https://github.com/QuantConnect/Lean/assets/47573394/3f282e3f-7ee8-4d43-b6ad-eb96e59a4ee3)
[KrakenCashBalanceBugLogs.txt](https://github.com/user-attachments/files/15742240/KrakenCashBalanceBugLogs.txt)

**Comment by Martin-Molinero** [comment]
Shipping fix at https://github.com/QuantConnect/Lean.Brokerages.Kraken/pull/48, starting from version 16546
