### ISSUE TITLE
Library Request: cuDF + RAPIDS

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#8318]
[cuDF](https://github.com/rapidsai/cudf) (pronounced "KOO-dee-eff") is a GPU DataFrame library for loading, joining, aggregating, filtering, and otherwise manipulating data.

Test:

```python
import cudf

tips_df = cudf.read_csv("https://github.com/plotly/datasets/raw/master/tips.csv")
tips_df["tip_percentage"] = tips_df["tip"] / tips_df["total_bill"] * 100

# display average tip by dining party size
print(tips_df.groupby("size").tip_percentage.mean())
```

Gives us:

> No module named 'cudf'

EDIT: We need to [install RAPIDS](https://docs.rapids.ai/install/) too.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by beckernick** [comment]
Hi! I came across this issue due to the cuDF reference. I work on cuDF and other [RAPIDS projects at NVIDIA](https://developer.nvidia.com/rapids).

In addition to being a GPU library, cuDF can provide zero code change GPU-acceleration for [pandas](https://rapids.ai/cudf-pandas/) and (as of yesterday) [Polars](https://rapids.ai/polars-gpu-engine/).

```python
%load_ext cudf.pandas # or via command line for Python scripts

df = pd.read_parquet(filepath)

(df[["Registration State", "Violation Description"]]
 .value_counts()
 .groupby("Registration State")
 .head(1)
 .sort_index()
 .reset_index()
)
```

```python
import polars as pl

ldf = pl.LazyFrame({"a": [1.242, 1.535]})

print(
    ldf.select(
        pl.col("a").round(1)
    ).collect(engine="gpu")
)
```

Would love to see these capabilities available for LEAN users. Happy to try to help answer any questions that might come up if you or anyone else explores this.

**Comment by Martin-Molinero** [comment]
We will be adding these libraries to cloud only default environment due to the large footprint required (~8GB)
