### ISSUE TITLE
ETrade API

### ISSUE THREAD

**Issue by bmsapp** [QuantConnect/Lean#923]
Anyone care to integrate with the ETrade REST API?

**Comment by ballance** [comment]
I've worked with the E*Trade API quite a bit.  The problem is that they make you go to a website and pick up an auth code every 24 hours.  I've gotten them to extend my account to 30 days, but it was a bit of a hassle.  Would be great to have a way to not need to do this.  Glad to help out with integration of this into Lean.

**Comment by bmsapp** [comment]
Here is the gist of web-scraping the login form: 

https://gist.github.com/bmsapp/b42bab337c049bf498bc16172e8ddbc6

Occassionally there will be an alternate splash screen after login, for the user to renew agreements or account settings. There is no detection or handling of that situation or planned outages of the API. It has been an occasional issue, maybe once each quarter, which is resolved by me logging in directly to the ETrade website to take care of whatever it is.
