### ISSUE TITLE
Options: Daily backtesting

### ISSUE THREAD

**Issue by bobobo1618** [QuantConnect/Lean#941]
Per https://github.com/QuantConnect/Lean/issues/939, backtesting options strategies with daily resolution is not currently supported, only minute.

It'd be good if daily was supported.

**Comment by tetious** [comment]
This is fairly confusing for folks new to the platform, mainly because the data library documentation page claims support for Daily, Hourly and Minute resolutions. We spent many hours spinning on this, assuming we were doing something wrong. :)

I suggest a you note this in the documentation and that you correct the data page (https://www.quantconnect.com/data#options/usa/price).

**Comment by jaredbroad** [comment]
Sorry about that @tetious! Will fix it today.

**Comment by mathpaquette** [comment]
Guys, I wish to have second resolution for Options. Do you see any problem? Plan to add support for in for IQFeed.

@jaredbroad
